BEGIN TRANSACTION;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT * 
FROM OPENQUERY([10.1.0.8] , 'SELECT [PK_empresa_empleado_contrato]
      ,[cod_empr]
      ,[cod_empl]
      ,[nro_cont]
      ,[cod_niv1]
      ,[cod_niv2]
      ,[cod_niv3]
      ,[cod_niv4]
      ,[cod_nive]
      ,[EMPRESA_OLD]
      ,[EMPRESA]
      ,[CIUDAD]
      ,[CIUDAD_CONTRATO]
      ,[CARGO]
      ,[fec_cont]
      ,[fec_ingr]
      ,[sue_basi]
      ,[ind_acti]
      ,[nom_empl]
      ,[cod_mdej]
      ,[ape_empl]
      ,[sex_empl]
      ,[fec_naci]
      ,[est_civi]
      ,[tit_obte]
      ,[per_carg]
      ,[gra_educ]
      ,[pro_titu]
      ,[box_mail]
      ,[eee_mail]
      ,[dir_resi]
      ,[bar_resi]
      ,[tel_resi]
      ,[nom_pais]
      ,[nom_mpio]
      ,[edad_Empleado]
      ,[nom_carg]
      ,[fec_venc_2]
      ,[fec_venc]
      ,[duracion]
      ,[cod_ccos]
      ,[nom_ccos]
      ,[cod_niv5]
      ,[Expr1]
      ,[NIT_CLIE]
      ,[idEmpresa]
      ,[Empresa_Empleado]
      ,[NIT_Empresa_Empleado]
      ,[tipoContrato]
      ,[Area]
      ,[Dpto_Residencia]
      ,[pro_fesi]
      ,[años_expe]
      ,[COD_RAZA]
      ,[cod_nacionalidad]
      ,[nom_nacionalidad]
      ,[CedulaJefe]
      ,[NombreJefe]
      ,[Fuero_Pensional]
      ,[Centro_trabajo]
      ,[Ciudad_centro_trabajo]
  FROM [Kactus].[dbo].[QV_INFORMACION_USUARIOS_EMPLEADOS] WITH(NOLOCK)')
COMMIT TRANSACTION;