SELECT
CLI.CLI_NOMBRE,
ACT.ACT_NOMBRE,
ENC.ENC_NOMBRE,
REU.REU_CODIGO,
REU.RUT_CODIGO,
PRG.PRG_PREGUNTA,

CASE
WHEN RES.RES_RESPUESTA = '' THEN REU.REU_OBSERVACION
ELSE RES.RES_RESPUESTA
END AS RESPUESTA,

PRN.ENA_CODIGO,
REU.USUARIO_CREACION

FROM
SIM_RESPUESTA_USUARIO AS REU
INNER JOIN SIM_RESPUESTA AS RES ON (RES.RES_CODIGO=REU.RES_CODIGO)
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON (PRN.PRN_CODIGO=RES.PRN_CODIGO)
INNER JOIN SIM_PREGUNTA AS PRG ON (PRG.PRG_CODIGO=PRN.PRG_CODIGO)
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON (ENA.ENA_CODIGO=PRN.ENA_CODIGO)
INNER JOIN SIM_ENCUESTA AS ENC ON (ENC.ENC_CODIGO=ENA.ENC_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=ENA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)

WHERE
PRN.ENA_CODIGO IN (8246,8245,8247,8216,8214,8215,8249,8248,8250,8213,8212,8211)
AND ENC.ENC_NOMBRE = '2. MATERIAL IMPLEMENTADO'
AND (ENA.ESTADO=1 AND ENC.ESTADO=1)
AND CLI.CLI_CODIGO IN (212)

ORDER BY
REU.REU_CODIGO

/*-------------------------------------------------------------------*/

/*--1. MATERIAL RECIBIDO--*/

SELECT DISTINCT *

FROM (

SELECT
CLI.CLI_NOMBRE,
ACT.ACT_NOMBRE,
ENC.ENC_NOMBRE,
--REU.REU_CODIGO,
REU.RUT_CODIGO,
PRG.PRG_PREGUNTA,

CASE
WHEN RES.RES_RESPUESTA = '' THEN REU.REU_OBSERVACION
ELSE RES.RES_RESPUESTA
END AS RESPUESTA,

PRN.ENA_CODIGO,
REU.USUARIO_CREACION

FROM
SIM_RESPUESTA_USUARIO AS REU
INNER JOIN SIM_RESPUESTA AS RES ON (RES.RES_CODIGO=REU.RES_CODIGO)
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON (PRN.PRN_CODIGO=RES.PRN_CODIGO)
INNER JOIN SIM_PREGUNTA AS PRG ON (PRG.PRG_CODIGO=PRN.PRG_CODIGO)
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON (ENA.ENA_CODIGO=PRN.ENA_CODIGO)
INNER JOIN SIM_ENCUESTA AS ENC ON (ENC.ENC_CODIGO=ENA.ENC_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=ENA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)

WHERE
--PRN.ENA_CODIGO IN (8246,8245,8247,8216,8214,8215,8249,8248,8250,8213,8212,8211)
ENC.ENC_NOMBRE = '1. MATERIAL RECIBIDO'
AND (ENA.ESTADO=1 AND ENC.ESTADO=1)
AND CLI.CLI_CODIGO IN (212)

) AS ENC

PIVOT (

MAX(RESPUESTA)
FOR PRG_PREGUNTA IN ([REGIONAL],[OBSEQUIO RECIBIDO],[CANTIDAD RECIBIDA])

) AS PIVOTEAR

/*-------------------------------------------------------------------*/

/*--2. MATERIAL IMPLEMENTADO--*/

SELECT DISTINCT *

FROM (

SELECT
CLI.CLI_NOMBRE,
ACT.ACT_NOMBRE,
ENC.ENC_NOMBRE,
--REU.REU_CODIGO,
REU.RUT_CODIGO,
PRG.PRG_PREGUNTA,

CASE
WHEN RES.RES_RESPUESTA = '' THEN REU.REU_OBSERVACION
ELSE RES.RES_RESPUESTA
END AS RESPUESTA,

PRN.ENA_CODIGO,
REU.USUARIO_CREACION

FROM
SIM_RESPUESTA_USUARIO AS REU
INNER JOIN SIM_RESPUESTA AS RES ON (RES.RES_CODIGO=REU.RES_CODIGO)
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON (PRN.PRN_CODIGO=RES.PRN_CODIGO)
INNER JOIN SIM_PREGUNTA AS PRG ON (PRG.PRG_CODIGO=PRN.PRG_CODIGO)
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON (ENA.ENA_CODIGO=PRN.ENA_CODIGO)
INNER JOIN SIM_ENCUESTA AS ENC ON (ENC.ENC_CODIGO=ENA.ENC_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=ENA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)

WHERE
--PRN.ENA_CODIGO IN (8246,8245,8247,8216,8214,8215,8249,8248,8250,8213,8212,8211)
ENC.ENC_NOMBRE = '2. MATERIAL IMPLEMENTADO'
AND (ENA.ESTADO=1 AND ENC.ESTADO=1)
AND CLI.CLI_CODIGO IN (212)

) AS ENC

PIVOT (

MAX(RESPUESTA)
FOR PRG_PREGUNTA IN ([REGIONAL],[PDV IMPLEMENTADO],[OBSEQUIO IMPLEMENTADO],[CANTIDAD IMPLEMENTADA])

) AS PIVOTEAR
