SELECT
CLI.CLI_NOMBRE,
ACT.ACT_NOMBRE,
ENC.ENC_NOMBRE,
REU.REU_CODIGO,
REU.RUT_CODIGO,
PRG.PRG_PREGUNTA,

CASE
WHEN RES.RES_RESPUESTA = '' THEN REU.REU_OBSERVACION
ELSE RES.RES_RESPUESTA
END AS RESPUESTA,

PRN.ENA_CODIGO,
REU.USUARIO_CREACION

FROM
SIM_RESPUESTA_USUARIO AS REU
INNER JOIN SIM_RESPUESTA AS RES ON (RES.RES_CODIGO=REU.RES_CODIGO)
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON (PRN.PRN_CODIGO=RES.PRN_CODIGO)
INNER JOIN SIM_PREGUNTA AS PRG ON (PRG.PRG_CODIGO=PRN.PRG_CODIGO)
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON (ENA.ENA_CODIGO=PRN.ENA_CODIGO)
INNER JOIN SIM_ENCUESTA AS ENC ON (ENC.ENC_CODIGO=ENA.ENC_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=ENA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)

WHERE
PRN.ENA_CODIGO IN (8246,8245,8247,8216,8214,8215,8249,8248,8250,8213,8212,8211)
AND ENC.ENC_NOMBRE = '2. MATERIAL IMPLEMENTADO'
AND (ENA.ESTADO=1 AND ENC.ESTADO=1)
AND CLI.CLI_CODIGO IN (212)

ORDER BY
REU.REU_CODIGO

/*-------------------------------------------------------------------*/

/*--1. MATERIAL RECIBIDO--*/

SELECT DISTINCT *

FROM (

SELECT
CLI.CLI_NOMBRE,
ACT.ACT_NOMBRE,
ENC.ENC_NOMBRE,
--REU.REU_CODIGO,
REU.RUT_CODIGO,
PRG.PRG_PREGUNTA,

CASE
WHEN RES.RES_RESPUESTA = '' THEN REU.REU_OBSERVACION
ELSE RES.RES_RESPUESTA
END AS RESPUESTA,

PRN.ENA_CODIGO,
REU_CONSECUTIVO_ENC,
REU.USUARIO_CREACION

FROM
SIM_RESPUESTA_USUARIO AS REU
INNER JOIN SIM_RESPUESTA AS RES ON (RES.RES_CODIGO=REU.RES_CODIGO)
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON (PRN.PRN_CODIGO=RES.PRN_CODIGO)
INNER JOIN SIM_PREGUNTA AS PRG ON (PRG.PRG_CODIGO=PRN.PRG_CODIGO)
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON (ENA.ENA_CODIGO=PRN.ENA_CODIGO)
INNER JOIN SIM_ENCUESTA AS ENC ON (ENC.ENC_CODIGO=ENA.ENC_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=ENA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)

WHERE
--PRN.ENA_CODIGO IN (8246,8245,8247,8216,8214,8215,8249,8248,8250,8213,8212,8211)
ENC.ENC_NOMBRE = '1. MATERIAL RECIBIDO'
AND (ENA.ESTADO=1 AND ENC.ESTADO=1)
AND CLI.CLI_CODIGO IN (212)

) AS ENC

PIVOT (

MAX(RESPUESTA)
FOR PRG_PREGUNTA IN ([REGIONAL],[OBSEQUIO RECIBIDO],[CANTIDAD RECIBIDA])

) AS PIVOTEAR

/*-------------------------------------------------------------------*/

/*--2. MATERIAL IMPLEMENTADO--*/

SELECT DISTINCT *

FROM (

SELECT
CLI.CLI_NOMBRE,
ACT.ACT_NOMBRE,
ENC.ENC_NOMBRE,
--REU.REU_CODIGO,
REU.RUT_CODIGO,
PRG.PRG_PREGUNTA,

CASE
WHEN RES.RES_RESPUESTA = '' THEN REU.REU_OBSERVACION
ELSE RES.RES_RESPUESTA
END AS RESPUESTA,

PRN.ENA_CODIGO,
REU_CONSECUTIVO_ENC,
REU.USUARIO_CREACION

FROM
SIM_RESPUESTA_USUARIO AS REU
INNER JOIN SIM_RESPUESTA AS RES ON (RES.RES_CODIGO=REU.RES_CODIGO)
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON (PRN.PRN_CODIGO=RES.PRN_CODIGO)
INNER JOIN SIM_PREGUNTA AS PRG ON (PRG.PRG_CODIGO=PRN.PRG_CODIGO)
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON (ENA.ENA_CODIGO=PRN.ENA_CODIGO)
INNER JOIN SIM_ENCUESTA AS ENC ON (ENC.ENC_CODIGO=ENA.ENC_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=ENA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)

WHERE
--PRN.ENA_CODIGO IN (8246,8245,8247,8216,8214,8215,8249,8248,8250,8213,8212,8211)
ENC.ENC_NOMBRE = '2. MATERIAL IMPLEMENTADO'
AND (ENA.ESTADO=1 AND ENC.ESTADO=1)
AND CLI.CLI_CODIGO IN (212)

) AS ENC

PIVOT (

MAX(RESPUESTA)
FOR PRG_PREGUNTA IN ([REGIONAL],[PDV IMPLEMENTADO],[OBSEQUIO IMPLEMENTADO],[CANTIDAD IMPLEMENTADA])

) AS PIVOTEAR

/*-------------------------------------------------------------------*/
/*--PANLE PURINA--*/

SELECT DISTINCT

PVC.PDV_CODIGO,
PVC.PVC_NOMBRE_PDV,
PDV.CIU_CODIGO,
CIU.CIU_NOMBRE,
T7.TIP_NOMBRE AS REGIONAL,
T1.TIP_NOMBRE AS TIPO_PUNTO_VENTA,
T2.TIP_NOMBRE AS ZONA,
T3.TIP_NOMBRE AS CANAL,
T5.TIP_NOMBRE AS SUB_CADENA,
T6.TIP_NOMBRE AS CADENA

FROM
SIM_PUNTO_VENTA_CLIENTE AS PVC
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=PVC.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)
INNER JOIN SIM_TIPO AS T1 ON (T1.TIP_CODIGO=PVC.TIP_CODIGO)
INNER JOIN SIM_TIPO AS T2 ON (T2.TIP_CODIGO=PVC.TIP_CODIGO2)
INNER JOIN SIM_TIPO AS T3 ON (T3.TIP_CODIGO=PVC.TIP_CODIGO3)
INNER JOIN SIM_TIPO AS T5 ON (T5.TIP_CODIGO=PVC.TIP_CODIGO5)
INNER JOIN SIM_TIPO AS T6 ON (T6.TIP_CODIGO=PVC.TIP_CODIGO6)
INNER JOIN SIM_PUNTO_VENTA AS PDV ON (PDV.PDV_CODIGO=PVC.PDV_CODIGO)
INNER JOIN SIM_CIUDAD AS CIU ON (CIU.CIU_CODIGO=PDV.CIU_CODIGO)
FULL JOIN SIM_REGIONAL_CIUDAD AS REC ON (REC.CLI_CODIGO=CLI.CLI_CODIGO AND REC.CIU_CODIGO=CIU.CIU_CODIGO)
INNER JOIN SIM_TIPO AS T7 ON (T7.TIP_CODIGO=REC.TIP_CODIGO)

WHERE
CLI.CLI_CODIGO=212
AND (PVC.ESTADO=1 AND ACT.ESTADO=1)
