WITH MARCAS AS (
        /*SIM_ACTIVIDAD_COMERCIAL*/
        SELECT FOT.FOT_CODIGO,FOA.ACO_CODIGO AS PK_CODIGO, ACO.MAR_CODIGO
        FROM
            SIM_FOTO AS FOT
            INNER JOIN SIM_FOTO_ASOCIACION AS FOA ON FOA.FOT_CODIGO=FOT.FOT_CODIGO AND FOA.ESTADO=1 AND FOA.ACO_CODIGO IS NOT NULL
            INNER JOIN SIM_ACTIVIDAD_COMERCIAL AS ACO ON ACO.ACO_CODIGO=FOA.ACO_CODIGO AND ACO.ESTADO=1
        WHERE
            FOT.ESTADO=1 AND CONVERT(DATE,FOT.FECHA_CREACION)>='2024-02-01'
        UNION
        /*SIM_GESTION_EXHIBICION*/
        SELECT
            FOT.FOT_CODIGO,FOA.GEE_CODIGO,GEE.MAR_CODIGO
        FROM
            SIM_FOTO AS FOT
            INNER JOIN SIM_FOTO_ASOCIACION AS FOA ON FOA.FOT_CODIGO=FOT.FOT_CODIGO AND FOA.ESTADO=1 AND FOA.GEE_CODIGO IS NOT NULL
            INNER JOIN SIM_GESTION_EXHIBICION AS GEE ON GEE.GEE_CODIGO=FOA.GEE_CODIGO AND GEE.ESTADO=1 AND GEE.MAR_CODIGO IS NOT NULL
        WHERE
            FOT.ESTADO=1 AND CONVERT(DATE,FOT.FECHA_CREACION)>='2024-02-01'
        UNION
        /*SIM_CARAS*/
        SELECT
            FOT.FOT_CODIGO,FOA.CAR_CODIGO,CAR.MAR_CODIGO
        FROM
            SIM_FOTO AS FOT
            INNER JOIN SIM_FOTO_ASOCIACION AS FOA ON FOA.FOT_CODIGO=FOT.FOT_CODIGO AND FOA.ESTADO=1 AND FOA.CAR_CODIGO IS NOT NULL
            INNER JOIN SIM_CARAS AS CAR ON CAR.CAR_CODIGO=FOA.CAR_CODIGO AND CAR.ESTADO=1 AND CAR.MAR_CODIGO IS NOT NULL
        WHERE
            FOT.ESTADO=1 AND CONVERT(DATE,FOT.FECHA_CREACION)>='2024-02-01'),
/*SIM_RESPUESTA_USUARIO*/
     CATEGORIAS_REU AS (
    SELECT DISTINCT
        PRA.ACT_CODIGO,
        CAT.CAT_NOMBRE
    FROM 
            SIM_ACTIVIDAD AS ACT
            INNER JOIN SIM_PRODUCTO_ACTIVIDAD AS PRA ON ACT.ACT_CODIGO=PRA.ACT_CODIGO AND PRA.ESTADO = 1
            INNER JOIN SIM_CATEGORIA AS CAT ON CAT.CAT_CODIGO = PRA.CAT_CODIGO
            INNER JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO = PRA.PRO_CODIGO
            INNER JOIN SIM_MARCA AS MAR ON MAR.MAR_CODIGO = PRO.MAR_CODIGO AND MAR.MAR_PROPIA = 1 AND MAR.ESTADO = 1
    WHERE 
        ACT.ESTADO=1)
SELECT
    FOT.RUT_CODIGO,
    FOT.FOT_CODIGO,
    FOT.FOT_RUTA AS URL_FOTO,
    FOT.TIP_CODIGO AS TIPO_TAREA,
    T1.TIP_NOMBRE AS NOMBRE_TAREA,
    RUT.CLI_NOMBRE,
    RUT.ACT_NOMBRE,
    STRING_AGG(CAT.CAT_NOMBRE, ',') AS CATEGORIA,
    FOT.FECHA_CREACION,
    FOT.FECHA_MODIFICACION
FROM 
    SIM_FOTO AS FOT 
    INNER JOIN ( 
        SELECT
            CLI.CLI_CODIGO,
            CLI.CLI_NOMBRE,
            ACT.ACT_CODIGO,
            ACT.ACT_NOMBRE,
            RUT.RUT_CODIGO
        FROM
            SIM_CLIENTE AS CLI
            INNER JOIN SIM_ACTIVIDAD AS ACT ON CLI.CLI_CODIGO = ACT.CLI_CODIGO AND ACT.ESTADO=1
            INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON ACT.ACT_CODIGO = USA.ACT_CODIGO
            INNER JOIN SIM_RUTA AS RUT ON USA.USA_CODIGO = RUT.USA_CODIGO AND RUT.ESTADO=1
        WHERE
            CLI.ESTADO=1 ) AS RUT ON RUT.RUT_CODIGO=FOT.RUT_CODIGO
    INNER JOIN SIM_TIPO AS T1 ON T1.TIP_CODIGO=FOT.TIP_CODIGO
    INNER JOIN MARCAS AS MAR ON MAR.FOT_CODIGO=FOT.FOT_CODIGO
    INNER JOIN (
        SELECT DISTINCT MAR.MAR_CODIGO, CAT.CAT_NOMBRE
        FROM
            SIM_MARCA AS MAR
            INNER JOIN SIM_PRODUCTO AS PRO ON PRO.MAR_CODIGO=MAR.MAR_CODIGO
            INNER JOIN SIM_PRODUCTO_ACTIVIDAD AS PRA ON PRA.PRO_CODIGO=PRO.PRO_CODIGO
            INNER JOIN SIM_CATEGORIA AS CAT ON CAT.CAT_CODIGO=PRA.CAT_CODIGO) AS CAT ON CAT.MAR_CODIGO=MAR.MAR_CODIGO
WHERE RUT.CLI_CODIGO = 138 AND FOT.ESTADO = 1 AND CONVERT(DATE,FOT.FECHA_CREACION)>='2024-02-01'
GROUP BY 
FOT.RUT_CODIGO,FOT.FOT_CODIGO,FOT.FOT_RUTA,FOT.TIP_CODIGO,T1.TIP_NOMBRE,RUT.CLI_NOMBRE,RUT.ACT_NOMBRE,FOT.FECHA_CREACION,FOT.FECHA_MODIFICACION
UNION
/*CATEGORIAS ENCUESTA*/
SELECT
    FOT.RUT_CODIGO,
    FOT.FOT_CODIGO,
    FOT.FOT_RUTA AS URL_FOTO,
    FOT.TIP_CODIGO AS TIPO_TAREA,
    T1.TIP_NOMBRE AS NOMBRE_TAREA,
    RUT.CLI_NOMBRE,
    RUT.ACT_NOMBRE,
    STRING_AGG(CAT_NOMBRE, ',') AS CATEGORIA,
    FOT.FECHA_CREACION,
    FOT.FECHA_MODIFICACION
FROM 
    SIM_FOTO AS FOT 
    INNER JOIN SIM_FOTO_ASOCIACION AS FOA ON FOA.FOT_CODIGO=FOT.FOT_CODIGO AND FOA.REU_CODIGO IS NOT NULL AND FOA.ESTADO=1
    INNER JOIN ( 
        SELECT
            CLI.CLI_CODIGO,
            CLI.CLI_NOMBRE,
            ACT.ACT_CODIGO,
            ACT.ACT_NOMBRE,
            RUT.RUT_CODIGO
        FROM
            SIM_CLIENTE AS CLI
            INNER JOIN SIM_ACTIVIDAD AS ACT ON CLI.CLI_CODIGO = ACT.CLI_CODIGO AND ACT.ESTADO=1
            INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON ACT.ACT_CODIGO = USA.ACT_CODIGO
            INNER JOIN SIM_RUTA AS RUT ON USA.USA_CODIGO = RUT.USA_CODIGO AND RUT.ESTADO=1
        WHERE
            CLI.ESTADO=1 ) AS RUT ON RUT.RUT_CODIGO=FOT.RUT_CODIGO
    INNER JOIN SIM_TIPO AS T1 ON T1.TIP_CODIGO=FOT.TIP_CODIGO
    INNER JOIN CATEGORIAS_REU AS CAT ON CAT.ACT_CODIGO=RUT.ACT_CODIGO
WHERE RUT.CLI_CODIGO = 138 AND FOT.ESTADO = 1 AND CONVERT(DATE,FOT.FECHA_CREACION)>='2024-02-01'
GROUP BY 
FOT.RUT_CODIGO,FOT.FOT_CODIGO,FOT.FOT_RUTA,FOT.TIP_CODIGO,T1.TIP_NOMBRE,RUT.CLI_NOMBRE,RUT.ACT_NOMBRE,FOT.FECHA_CREACION,FOT.FECHA_MODIFICACION