SELECT
FOT.FOT_CODIGO,
FOT.TIP_CODIGO,
T1.TIP_NOMBRE AS FOT_MODULO,
FOT.TIP_CODIGO2,
T2.TIP_NOMBRE AS TIPO_EXHIBICION,
FOT.TIP_CODIGO3,
T3.TIP_NOMBRE AS TIPO_FOTO_LIBRE,
FOT.RUT_CODIGO,
FOT.FOT_NOMBRE,
FOT.FOT_RUTA,
--FOT.FOT_DESCRIPCION,
FOA.FOA_CODIGO,
--FOA.FOT_CODIGO,
--FOA.EXH_CODIGO,
--FOA.ACO_CODIGO,
--FOA.AUD_CODIGO,
FOA.ENA_CODIGO,
ENC.ENC_NOMBRE,
--FOA.ACI_CODIGO,
FOA.GEE_CODIGO,
--FOA.SGE_CODIGO,
--FOA.FOR_CODIGO,
FOA.REU_CONSECUTIVO_ENC,
FOA.REU_CODIGO
--FOA.CAR_CODIGO,
--FOA.VEC_CODIGO
FROM
SIM_FOTO AS FOT
LEFT JOIN SIM_FOTO_ASOCIACION AS FOA ON FOA.FOT_CODIGO=FOT.FOT_CODIGO AND FOA.ESTADO=1
INNER JOIN SIM_RUTA AS RUT ON RUT.RUT_CODIGO=FOT.RUT_CODIGO AND RUT.ESTADO=1
LEFT JOIN SIM_TIPO AS T1 ON T1.TIP_CODIGO=FOT.TIP_CODIGO
LEFT JOIN SIM_TIPO AS T2 ON T2.TIP_CODIGO=FOT.TIP_CODIGO2
LEFT JOIN SIM_TIPO AS T3 ON T3.TIP_CODIGO=FOT.TIP_CODIGO3
LEFT JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON ENA.ENA_CODIGO=FOA.ENA_CODIGO
LEFT JOIN SIM_ENCUESTA AS ENC ON ENC.ENC_CODIGO=ENA.ENC_CODIGO
WHERE
FOT.ESTADO=1 AND 
RUT.USA_CODIGO IN (SELECT USA_CODIGO FROM SIM_USUARIO_ACTIVIIDAD WHERE ACT_CODIGO IN (774)) 

-------------------------------------------------------------------

SELECT
USA.ACT_CODIGO,
ACT.ACT_NOMBRE,
FOT.FOT_CODIGO,
FOT.RUT_CODIGO,
RUT.PDV_CODIGO,
CONVERT(DATE,RUT.RUT_FECHA_RUTA) AS RUT_FECHA_RUTA,
FOT.FOT_NOMBRE,
FOT.FOT_RUTA,
FOT.FOT_DESCRIPCION,
FOA.FOA_CODIGO,
FOA.ACO_CODIGO,
ACO.MAR_CODIGO,
ACO.TIP_CODIGO,
T1.TIP_NOMBRE AS ACTIVIDAD_COMERCIAL,
ACO.TIP_CODIGO2,
T2.TIP_NOMBRE AS CATEGORIA,
MAR.MAR_CODIGO,
ACO.ACO_MARCA_ABIERTA,
FOT.USUARIO_CREACION

FROM
SIM_FOTO AS FOT
LEFT JOIN SIM_FOTO_ASOCIACION AS FOA ON FOA.FOT_CODIGO=FOT.FOT_CODIGO AND FOA.ESTADO=1
INNER JOIN SIM_RUTA AS RUT ON RUT.RUT_CODIGO=FOT.RUT_CODIGO AND RUT.ESTADO=1
INNER JOIN SIM_ACTIVIDAD_COMERCIAL AS ACO ON ACO.ACO_CODIGO=FOA.ACO_CODIGO AND ACO.ESTADO=1
INNER JOIN SIM_TIPO AS T1 ON T1.TIP_CODIGO=ACO.TIP_CODIGO
INNER JOIN SIM_TIPO AS T2 ON T2.TIP_CODIGO=ACO.TIP_CODIGO2
INNER JOIN SIM_MARCA AS MAR ON MAR.MAR_CODIGO=ACO.MAR_CODIGO
INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON USA.USA_CODIGO=RUT.USA_CODIGO
INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.ACT_CODIGO=USA.ACT_CODIGO

WHERE
FOT.ESTADO=1 AND 
RUT.USA_CODIGO IN (SELECT USA_CODIGO FROM SIM_USUARIO_ACTIVIIDAD WHERE ACT_CODIGO IN (738)) AND
T1.TIP_NOMBRE LIKE '%CONCURSO%'