--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
DECLARE @FECHA_RUT_INICIO DATE,@FECHA_RUT_FIN DATE , @ACT_CODIGO INT 
SET @FECHA_RUT_INICIO='2023-11-01'
SET @FECHA_RUT_FIN='2023-12-31'
SET @ACT_CODIGO=684

SELECT

PANEL.ACT_NOMBRE AS ACTIVIDAD,
PANEL.REGIONAL AS REGIONAL,
PANEL.CIU_NOMBRE AS CIUDAD,
PANEL.CANAL AS CANAL,
PANEL.CADENA AS CADENA,
PANEL.SUB_CADENA AS 'SUB CADENA',
PANEL.ZONA AS ZONA,
PANEL.PDV_CODIGO AS 'PDV CODIGO',
PANEL.PVC_NOMBRE_PDV AS 'NOMBRE COMERCIAL',
PANEL.PDV_CODIGO_EAN AS 'CODIGO EAN',
TIPO_PUNTO_VENTA AS 'TIPO PDV',

CAR.CAR_CODIGO AS 'CARAS CODIGO',
CAR.ENP_CODIGO AS 'PARRILLA CODIGO',
CAR.MAR_CODIGO AS 'MARCA CODIGO',
MAR.MAR_NOMBRE AS MARCA,
CAR.CAT_CODIGO AS 'CATEGORIA CODIGO',
CAT.CAT_NOMBRE AS CATEGORIA,
CONVERT(INT,CAR.CAR_CANTIDAD_CARAS) AS 'CANTIDAD CARAS',
CAR.CAR_UNIVERSO AS 'UNIVERSO',
CAR.TIP_CODIGO_CAUSAL AS 'CODIGO CAUSAL',
T1.TIP_NOMBRE AS CAUSAL,
CAR.CAR_CUMPLIMIENTO AS 'CARAS CUMPLIMIENTO',
CAR.CAR_PARTICIPACION AS 'CARAS PARTICIPACION',
--CAR.CAR_OBJETIVO_UNIVERSO AS 'OBJETIVO UNIVERSO',
MAO.MAO_OBJETIVO AS 'OBJETIVO UNIVERSO',
FLOOR(CAR.CAR_UNIVERSO * MAO.MAO_OBJETIVO/100) AS 'CARAS MINIMAS EN EL LINEAL',
CAR.CAR_FALTANTE AS 'CARAS FALTANTE',
STRING_AGG(FOT.FOT_CODIGO,'-ALIMENTOS POLAR, ') +'-ALIMENTOS POLAR' AS 'FOTO CODIGO',
STRING_AGG(FOT.FOT_NOMBRE,', ') AS 'FOTO NOMBRE',
STRING_AGG(FOT.FOT_RUTA,', ') AS 'FOTO RUTA',
CAR.RUT_CODIGO AS 'RUTA CODIGO',
CONVERT(DATE,RUT.RUT_FECHA_RUTA) AS 'RUTA FECHA',

USUARIOS.USU_LOGIN AS 'USUARIO',
USUARIOS.NOMBRE_COMPLETO AS 'NOMBRE USUARIO',
USUARIOS.USU_LOGIN_JEFE AS 'USUARIO SUPERVISOR',
USUARIOS.NOMBRE_COMPLETO_JEFE AS 'NOMBRE SUPERVISOR'

FROM
SIM_CARAS AS CAR WITH (NOLOCK)
INNER JOIN SIM_ENCABEZADO_PARRILLA AS DEP ON (DEP.ENP_CODIGO=CAR.ENP_CODIGO)
INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON (ACA.ACA_CODIGO=DEP.ACA_CODIGO AND ACA.APV_CODIGO=50)
INNER JOIN SIM_RUTA AS RUT WITH (NOLOCK) ON (RUT.RUT_CODIGO=CAR.RUT_CODIGO)
FULL JOIN SIM_TIPO AS T1 ON (T1.TIP_CODIGO=CAR.TIP_CODIGO_CAUSAL)
INNER JOIN (
SELECT

PVC.PVC_CODIGO,
PVC.PDV_CODIGO,
CIU.CIU_CODIGO,
CIU_NOMBRE,
REC.TIP_CODIGO AS REGIONAL_CODIGO,
T7.TIP_NOMBRE AS REGIONAL,
PVC.ACT_CODIGO,
ACT.ACT_NOMBRE,
PVC.TIP_CODIGO AS TIPO_PUNTO_VENTA_CODIGO,
T1.TIP_NOMBRE AS TIPO_PUNTO_VENTA,
PVC.TIP_CODIGO2 AS ZONA_CODIGO,
T2.TIP_NOMBRE AS ZONA,
PVC.TIP_CODIGO3 AS CANAL_CODIGO,
T3.TIP_NOMBRE AS CANAL,
PVC.PVC_CODIGO_COPIDROGAS,
PVC.PVC_CODIGO_ISM,
PVC.PVC_CODIGO_EAN,
PDV.PDV_CODIGO_EAN,
PVC.PVC_CODIGO_NIELSEN,
PVC.PVC_CODIGO_OPCIONAL1,
PVC.PVC_CODIGO_OPCIONAL2,
PVC.PVC_CODIGO_CEM,
PVC.PVC_CODIGO_BRIEF,
PVC.PVC_CODIGO_SAP,
PVC.PVC_VENDEDOR,
PVC.PVC_DISTRIBUIDOR,
PVC.FECHA_ACTIVACION,
PVC.FECHA_INACTIVACION,
PVC.TIP_CODIGO4 AS RV_CODIGO,
T4.TIP_NOMBRE AS RV,
PVC.PVC_NOMBRE_PDV,
PVC.TIP_CODIGO5 AS SUB_CADENA_CODIGO,
T5.TIP_NOMBRE AS SUB_CADENA,
PVC.TIP_CODIGO6 AS CADENA_CODIGO,
T6.TIP_NOMBRE AS CADENA,
PVC.TIP_CODIGO7,
PVC.TIP_CODIGO8,
PVC.WTA_NRO_VISITAS_ACEPTADAS,
PVC.WTA_NRO_VISITAS,
PVC.WTA_CODIGO

FROM
SIM_PUNTO_VENTA_CLIENTE AS PVC WITH (NOLOCK)
FULL JOIN SIM_TIPO AS T1 ON (T1.TIP_CODIGO=PVC.TIP_CODIGO)
FULL JOIN SIM_TIPO AS T2 ON (T2.TIP_CODIGO=PVC.TIP_CODIGO2)
FULL JOIN SIM_TIPO AS T3 ON (T3.TIP_CODIGO=PVC.TIP_CODIGO3)
FULL JOIN SIM_TIPO AS T4 ON (T4.TIP_CODIGO=PVC.TIP_CODIGO4)
FULL JOIN SIM_TIPO AS T5 ON (T5.TIP_CODIGO=PVC.TIP_CODIGO5)
FULL JOIN SIM_TIPO AS T6 ON (T6.TIP_CODIGO=PVC.TIP_CODIGO6)
INNER JOIN SIM_PUNTO_VENTA AS PDV ON (PDV.PDV_CODIGO=PVC.PDV_CODIGO)
INNER JOIN SIM_CIUDAD AS CIU ON (CIU.CIU_CODIGO=PDV.CIU_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=PVC.ACT_CODIGO)
FULL JOIN SIM_REGIONAL_CIUDAD AS REC ON (REC.CIU_CODIGO=PDV.CIU_CODIGO AND REC.CLI_CODIGO=ACT.CLI_CODIGO)
FULL JOIN SIM_TIPO AS T7 ON (T7.TIP_CODIGO=REC.TIP_CODIGO)

WHERE
T1.ESTADO=1 AND PVC.ESTADO=1 AND REC.ESTADO=1 AND PDV.ESTADO=1 AND
PVC.ACT_CODIGO=@ACT_CODIGO
) AS PANEL ON (PANEL.PDV_CODIGO=RUT.PDV_CODIGO AND PANEL.ACT_CODIGO=ACA.ACT_CODIGO)
INNER JOIN (
SELECT DISTINCT
    CLI.CLI_CODIGO,
    CLI.CLI_NOMBRE,
    ACT.ACT_CODIGO,
    ACT.ACT_NOMBRE,
    USU.USU_NUMERO_DOCUMENTO AS DOCUMENTO,
    USU.USU_NOMBRES + ' ' + USU.USU_APELLIDOS AS NOMBRE_COMPLETO,
    USU.USU_LOGIN,
    PER.PER_CODIGO,
    PER.PER_NOMBRE,
    USU.USU_CODIGO,
    USC.USC_CODIGO,
    USA.USA_CODIGO,
    ACT.ESTADO AS ESTADO_ACT,
    CLI.ESTADO AS ESTADO_CLI,
    USU.ESTADO AS ESTADO_USU,
    USC.ESTADO AS ESTADO_USC,
    USA.ESTADO AS ESTADO_USA,
    PEU.ESTADO AS ESTADO_PER,
    UAE.UAE_CODIGO,
    UAE.TIP_CODIGO AS TIP_CARGO,
    TIP2.TIP_NOMBRE AS TIP_CARGO_CARGO,
    USU2.USU_NUMERO_DOCUMENTO AS DOCUMENTO_JEFE,
    USU2.USU_NOMBRES + ' ' + USU2.USU_APELLIDOS AS NOMBRE_COMPLETO_JEFE,
    USU2.USU_LOGIN AS USU_LOGIN_JEFE,
    PER2.PER_CODIGO AS PER_CODIGO_JEFE,
    PER2.PER_NOMBRE AS PER_NOMBRE_JEFE,
    USU2.USU_CODIGO AS USU_CODIGO_JEFE,
    USC2.USC_CODIGO AS USC_CODIGO_JEFE,
    USA2.USA_CODIGO AS USA_CODIGO_JEFE,
    UAE.ESTADO AS ESTADO_UAE_JEFE,
    USU2.ESTADO AS ESTADO_USU_JEFE
FROM dbo.SIM_USUARIO AS USU WITH (NOLOCK)
INNER JOIN dbo.SIM_USUARIO_CLIENTE AS USC WITH (NOLOCK) ON USU.USU_CODIGO = USC.USU_CODIGO
INNER JOIN dbo.SIM_USUARIO_ACTIVIIDAD AS USA WITH (NOLOCK) ON USA.USC_CODIGO = USC.USC_CODIGO
INNER JOIN dbo.SIM_PERFIL_USUARIO AS PEU WITH (NOLOCK) ON PEU.USA_CODIGO = USA.USA_CODIGO
INNER JOIN dbo.SIM_PERFIL AS PER WITH (NOLOCK) ON PER.PER_CODIGO = PEU.PER_CODIGO
INNER JOIN dbo.SIM_ACTIVIDAD AS ACT WITH (NOLOCK) ON ACT.ACT_CODIGO = USA.ACT_CODIGO
INNER JOIN dbo.SIM_CLIENTE AS CLI WITH (NOLOCK) ON CLI.CLI_CODIGO = ACT.CLI_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO_ACTIVIDAD_ENCARGADO AS UAE WITH (NOLOCK) ON UAE.USA_CODIGO2 = USA.USA_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO_ACTIVIIDAD AS USA2 WITH (NOLOCK) ON UAE.USA_CODIGO = USA2.USA_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO_CLIENTE AS USC2 WITH (NOLOCK) ON USA2.USC_CODIGO = USC2.USC_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO AS USU2 WITH (NOLOCK) ON USU2.USU_CODIGO = USC2.USU_CODIGO 
FULL OUTER JOIN dbo.SIM_PERFIL_USUARIO AS PEU2 WITH (NOLOCK) ON PEU2.USA_CODIGO = USA2.USA_CODIGO 
FULL OUTER JOIN dbo.SIM_PERFIL AS PER2 WITH (NOLOCK) ON PER2.PER_CODIGO = PEU2.PER_CODIGO 
FULL OUTER JOIN dbo.SIM_TIPO AS TIP2 WITH (NOLOCK) ON TIP2.TIP_CODIGO = UAE.TIP_CODIGO

WHERE
USU.ESTADO = 1 AND USA.ESTADO=1 AND (UAE.ESTADO=1 OR UAE.ESTADO IS NULL) AND UAE.TIP_CODIGO=59
AND ACT.ACT_CODIGO=@ACT_CODIGO
) AS USUARIOS ON (USUARIOS.USA_CODIGO=RUT.USA_CODIGO)
INNER JOIN SIM_MARCA AS MAR WITH (NOLOCK) ON (CAR.MAR_CODIGO=MAR.MAR_CODIGO)
INNER JOIN SIM_CATEGORIA AS CAT WITH (NOLOCK) ON (CAT.CAT_CODIGO=CAR.CAT_CODIGO)
INNER JOIN SIM_MARCA_OBJETIVO AS MAO WITH (NOLOCK) ON (MAO.MAR_CODIGO=CAR.MAR_CODIGO AND MAO.PVC_CODIGO=PANEL.PVC_CODIGO AND MAO.ESTADO=1)
FULL JOIN SIM_FOTO_ASOCIACION AS FOA WITH (NOLOCK) ON (FOA.CAR_CODIGO=CAR.CAR_CODIGO)
FULL JOIN SIM_FOTO AS FOT WITH (NOLOCK) ON (FOT.FOT_CODIGO=FOA.FOT_CODIGO)

WHERE
CAR.ESTADO=1 AND
PANEL.ACT_CODIGO=@ACT_CODIGO AND 
CONVERT(DATE,RUT.RUT_FECHA_RUTA) BETWEEN @FECHA_RUT_INICIO AND @FECHA_RUT_FIN 
AND (MAO.MAO_FECHA_INICIO<=CAR.FECHA_CREACION AND MAO.MAO_FECHA_FIN>=CAR.FECHA_CREACION)

--AND CAR.RUT_CODIGO=21245107 AND CAR.CAT_CODIGO=4774
--AND CAR.CAR_CODIGO=47269340

GROUP BY

PANEL.ACT_NOMBRE,
PANEL.REGIONAL,
PANEL.CIU_NOMBRE,
PANEL.CANAL,
PANEL.CADENA,
PANEL.SUB_CADENA,
PANEL.ZONA,
PANEL.PDV_CODIGO,
PANEL.PVC_NOMBRE_PDV,
PANEL.PDV_CODIGO_EAN,
PANEL.TIPO_PUNTO_VENTA,
CAR.CAR_CODIGO,
CAR.ENP_CODIGO,
CAR.MAR_CODIGO,
MAR.MAR_NOMBRE,
CAR.CAT_CODIGO,
CAT.CAT_NOMBRE,
CAR.CAR_CANTIDAD_CARAS,
CAR.CAR_UNIVERSO,
CAR.TIP_CODIGO_CAUSAL,
T1.TIP_NOMBRE,
CAR.CAR_CUMPLIMIENTO,
CAR.CAR_PARTICIPACION,
MAO.MAO_OBJETIVO,
CAR.CAR_UNIVERSO,
CAR.CAR_FALTANTE,
CAR.RUT_CODIGO,
RUT.RUT_FECHA_RUTA,
USUARIOS.USU_LOGIN,
USUARIOS.NOMBRE_COMPLETO,
USUARIOS.USU_LOGIN_JEFE,
USUARIOS.NOMBRE_COMPLETO_JEFE

ORDER BY CAR.CAR_CODIGO
