--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
DECLARE @FECHA_RUT_INICIO DATE,@FECHA_RUT_FIN DATE , @ACT_CODIGO INT 
SET @FECHA_RUT_INICIO='2023-01-01'
SET @FECHA_RUT_FIN='2023-12-31'
SET @ACT_CODIGO=684

SELECT DISTINCT

PANEL.ACT_NOMBRE AS ACTIVIDAD,
PANEL.REGIONAL AS REGIONAL,
PANEL.CIU_NOMBRE AS CIUDAD,
PANEL.CANAL AS CANAL,
PANEL.CADENA AS CADENA,
PANEL.SUB_CADENA AS 'SUB CADENA',
PANEL.ZONA AS ZONA,
MAO.PVC_CODIGO AS 'PVC_CODIGO',
PANEL.PDV_CODIGO AS 'PDV CODIGO',
PANEL.PVC_NOMBRE_PDV AS 'NOMBRE COMERCIAL',
PANEL.PDV_CODIGO_EAN AS 'CODIGO EAN',
TIPO_PUNTO_VENTA AS 'TIPO PDV',


MAO.MAR_OBJETIVO_CODIGO AS 'MAO CODIGO',
MAO.MAR_CODIGO 'MARCA CODIGO',
MAR.MAR_NOMBRE AS MARCA,
CAT.CAT_CODIGO AS 'CATEGORIA CODIGO',
CAT.CAT_NOMBRE AS CATEGORIA,
MAO.MAO_OBJETIVO AS 'OBJETIVO',
CONVERT(DATE,MAO.MAO_FECHA_INICIO) AS 'FECHA INICIO OBJETIVO',
CONVERT(DATE,MAO.MAO_FECHA_FIN) AS 'FECHA FIN OBJETIVO'

FROM
SIM_CARAS AS CAR WITH (NOLOCK)
INNER JOIN SIM_ENCABEZADO_PARRILLA AS DEP ON (DEP.ENP_CODIGO=CAR.ENP_CODIGO)
INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON (ACA.ACA_CODIGO=DEP.ACA_CODIGO AND ACA.APV_CODIGO=50)
INNER JOIN SIM_RUTA AS RUT WITH (NOLOCK) ON (RUT.RUT_CODIGO=CAR.RUT_CODIGO)
INNER JOIN (
SELECT

PVC.PVC_CODIGO,
PVC.PDV_CODIGO,
CIU.CIU_CODIGO,
CIU_NOMBRE,
REC.TIP_CODIGO AS REGIONAL_CODIGO,
T7.TIP_NOMBRE AS REGIONAL,
PVC.ACT_CODIGO,
ACT.ACT_NOMBRE,
PVC.TIP_CODIGO AS TIPO_PUNTO_VENTA_CODIGO,
T1.TIP_NOMBRE AS TIPO_PUNTO_VENTA,
PVC.TIP_CODIGO2 AS ZONA_CODIGO,
T2.TIP_NOMBRE AS ZONA,
PVC.TIP_CODIGO3 AS CANAL_CODIGO,
T3.TIP_NOMBRE AS CANAL,
PVC.PVC_CODIGO_COPIDROGAS,
PVC.PVC_CODIGO_ISM,
PVC.PVC_CODIGO_EAN,
PDV.PDV_CODIGO_EAN,
PVC.PVC_CODIGO_NIELSEN,
PVC.PVC_CODIGO_OPCIONAL1,
PVC.PVC_CODIGO_OPCIONAL2,
PVC.PVC_CODIGO_CEM,
PVC.PVC_CODIGO_BRIEF,
PVC.PVC_CODIGO_SAP,
PVC.PVC_VENDEDOR,
PVC.PVC_DISTRIBUIDOR,
PVC.FECHA_ACTIVACION,
PVC.FECHA_INACTIVACION,
PVC.TIP_CODIGO4 AS RV_CODIGO,
T4.TIP_NOMBRE AS RV,
PVC.PVC_NOMBRE_PDV,
PVC.TIP_CODIGO5 AS SUB_CADENA_CODIGO,
T5.TIP_NOMBRE AS SUB_CADENA,
PVC.TIP_CODIGO6 AS CADENA_CODIGO,
T6.TIP_NOMBRE AS CADENA,
PVC.TIP_CODIGO7,
PVC.TIP_CODIGO8,
PVC.WTA_NRO_VISITAS_ACEPTADAS,
PVC.WTA_NRO_VISITAS,
PVC.WTA_CODIGO

FROM
SIM_PUNTO_VENTA_CLIENTE AS PVC WITH (NOLOCK)
FULL JOIN SIM_TIPO AS T1 ON (T1.TIP_CODIGO=PVC.TIP_CODIGO)
FULL JOIN SIM_TIPO AS T2 ON (T2.TIP_CODIGO=PVC.TIP_CODIGO2)
FULL JOIN SIM_TIPO AS T3 ON (T3.TIP_CODIGO=PVC.TIP_CODIGO3)
FULL JOIN SIM_TIPO AS T4 ON (T4.TIP_CODIGO=PVC.TIP_CODIGO4)
FULL JOIN SIM_TIPO AS T5 ON (T5.TIP_CODIGO=PVC.TIP_CODIGO5)
FULL JOIN SIM_TIPO AS T6 ON (T6.TIP_CODIGO=PVC.TIP_CODIGO6)
INNER JOIN SIM_PUNTO_VENTA AS PDV ON (PDV.PDV_CODIGO=PVC.PDV_CODIGO)
INNER JOIN SIM_CIUDAD AS CIU ON (CIU.CIU_CODIGO=PDV.CIU_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=PVC.ACT_CODIGO)
FULL JOIN SIM_REGIONAL_CIUDAD AS REC ON (REC.CIU_CODIGO=PDV.CIU_CODIGO AND REC.CLI_CODIGO=ACT.CLI_CODIGO)
FULL JOIN SIM_TIPO AS T7 ON (T7.TIP_CODIGO=REC.TIP_CODIGO)

WHERE
T1.ESTADO=1 AND PVC.ESTADO=1 AND REC.ESTADO=1 AND PDV.ESTADO=1 AND
PVC.ACT_CODIGO=@ACT_CODIGO
) AS PANEL ON (PANEL.PDV_CODIGO=RUT.PDV_CODIGO AND PANEL.ACT_CODIGO=ACA.ACT_CODIGO)

INNER JOIN SIM_MARCA_OBJETIVO AS MAO WITH (NOLOCK) ON (MAO.MAR_CODIGO=CAR.MAR_CODIGO AND MAO.PVC_CODIGO=PANEL.PVC_CODIGO AND MAO.ESTADO=1)
FULL JOIN SIM_MARCA AS MAR WITH (NOLOCK) ON (MAO.MAR_CODIGO=MAR.MAR_CODIGO)
FULL JOIN SIM_CATEGORIA AS CAT WITH (NOLOCK) ON (CAT.CAT_CODIGO=MAR.CAT_CODIGO)

WHERE
CAR.ESTADO=1 AND
PANEL.ACT_CODIGO=@ACT_CODIGO 
AND (MAO.MAO_FECHA_INICIO<=CAR.FECHA_CREACION AND MAO.MAO_FECHA_FIN>=CAR.FECHA_CREACION)
AND CONVERT(DATE,RUT.RUT_FECHA_RUTA) BETWEEN @FECHA_RUT_INICIO AND @FECHA_RUT_FIN

--AND CAR.RUT_CODIGO=21245107 AND CAR.CAT_CODIGO=4774
--AND MAO.PVC_CODIGO=1151090

ORDER BY MAO.PVC_CODIGO, CAT.CAT_CODIGO, MAO.MAR_CODIGO
