SELECT DISTINCT
CLI.CLI_NOMBRE AS CLIENTE,
ACT.ACT_NOMBRE AS ACTIVIDAD,
COUNT(RUT.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS RUTA,
COUNT(ACO.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS ACTIVIDAD_COMERCIAL,
COUNT(AGO.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS AGOTADO,
COUNT(AUD.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS AUDITORIA,
COUNT(CMA.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CAMBIO_MARCA,
COUNT(CAR.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CARAS,
COUNT(CPR.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CHEQUEO_PRECIO,
COUNT(EXI.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_EXHIBICION,
COUNT(FOT.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_FOTO,
COUNT(INV.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_INVENTARIO,
COUNT(NOA.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_NOTA,
COUNT(REU.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_RESPUESTA_USUARIO,
COUNT(REV.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_RUTERO_VALORIZADO,
COUNT(TRA.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_TRANSFERENCIA,
COUNT(VEC.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_VENCIMIENTO,
COUNT(VET.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_VENTAS,
COUNT(REC.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_RECORDATORIO,
COUNT(SER.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_SEGUIMIENTO_RECORDATORIO,
COUNT(CIT.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CITA,
COUNT(GEE.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_GESTION_EXHIBICION,
COUNT(EMO.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_ENCABEZADO_MOVIMIENTO,
COUNT(CHP.RUT_CODIGO) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CHEQUEO_PRECIO_ESPECIAL

FROM
SIM_RUTA AS RUT
INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON (USA.USA_CODIGO=RUT.USA_CODIGO)
INNER JOIN SIM_USUARIO_CLIENTE AS USC ON (USC.USC_CODIGO=USA.USC_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=USC.CLI_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.CLI_CODIGO=CLI.CLI_CODIGO)

FULL JOIN SIM_ACTIVIDAD_COMERCIAL AS ACO ON (ACO.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_AGOTADOS AS AGO ON (AGO.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_AUDITORIA AS AUD ON (AUD.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CAMBIO_MARCA AS CMA ON (CMA.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CARAS AS CAR ON (CAR.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CHEQUEO_PRECIO AS CPR ON (CPR.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_EXHIBICION AS EXI ON (EXI.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_FOTO AS FOT ON (FOT.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_INVENTARIO AS INV ON (INV.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_NOTA AS NOA ON (NOA.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_RESPUESTA_USUARIO AS REU ON (REU.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_RUTERO_VALORIZADO AS REV ON (REV.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_TRANSFERENCIA AS TRA ON (TRA.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_VENCIMIENTO AS VEC ON (VEC.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_VENTAS AS VET ON (VET.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_RECORDATORIO AS REC ON (REC.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_SEGUIMIENTO_RECORDATORIO AS SER ON (SER.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CITA AS CIT ON (CIT.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_GESTION_EXHIBICION AS GEE ON (GEE.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_ENCABEZADO_MOVIMIENTO AS EMO ON (EMO.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CHEQUEO_PRECIO_ESPECIAL AS CHP ON (CHP.RUT_CODIGO=RUT.RUT_CODIGO)

WHERE
USC.CLI_CODIGO IN (24,84) 

------------------------------------------
SELECT DISTINCT
CLI.CLI_NOMBRE AS CLIENTE,
ACT.ACT_NOMBRE AS ACTIVIDAD,
MAX(RUT.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS RUTA,
MAX(ACO.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS ACTIVIDAD_COMERCIAL,
MAX(AGO.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS AGOTADO,
MAX(AUD.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS AUDITORIA,
MAX(CMA.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CAMBIO_MARCA,
MAX(CAR.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CARAS,
MAX(CPR.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CHEQUEO_PRECIO,
MAX(EXI.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_EXHIBICION,
MAX(FOT.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_FOTO,
MAX(INV.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_INVENTARIO,
MAX(NOA.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_NOTA,
MAX(REU.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_RESPUESTA_USUARIO,
MAX(REV.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_RUTERO_VALORIZADO,
MAX(TRA.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_TRANSFERENCIA,
MAX(VEC.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_VENCIMIENTO,
MAX(VET.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_VENTAS,
MAX(REC.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_RECORDATORIO,
MAX(SER.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_SEGUIMIENTO_RECORDATORIO,
MAX(CIT.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CITA,
MAX(GEE.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_GESTION_EXHIBICION,
MAX(EMO.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_ENCABEZADO_MOVIMIENTO,
MAX(CHP.FECHA_CREACION) OVER (PARTITION BY CLI.CLI_CODIGO) AS SIM_CHEQUEO_PRECIO_ESPECIAL

FROM
SIM_RUTA AS RUT
INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON (USA.USA_CODIGO=RUT.USA_CODIGO)
INNER JOIN SIM_USUARIO_CLIENTE AS USC ON (USC.USC_CODIGO=USA.USC_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=USC.CLI_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.CLI_CODIGO=CLI.CLI_CODIGO)

FULL JOIN SIM_ACTIVIDAD_COMERCIAL AS ACO ON (ACO.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_AGOTADOS AS AGO ON (AGO.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_AUDITORIA AS AUD ON (AUD.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CAMBIO_MARCA AS CMA ON (CMA.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CARAS AS CAR ON (CAR.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CHEQUEO_PRECIO AS CPR ON (CPR.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_EXHIBICION AS EXI ON (EXI.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_FOTO AS FOT ON (FOT.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_INVENTARIO AS INV ON (INV.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_NOTA AS NOA ON (NOA.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_RESPUESTA_USUARIO AS REU ON (REU.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_RUTERO_VALORIZADO AS REV ON (REV.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_TRANSFERENCIA AS TRA ON (TRA.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_VENCIMIENTO AS VEC ON (VEC.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_VENTAS AS VET ON (VET.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_RECORDATORIO AS REC ON (REC.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_SEGUIMIENTO_RECORDATORIO AS SER ON (SER.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CITA AS CIT ON (CIT.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_GESTION_EXHIBICION AS GEE ON (GEE.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_ENCABEZADO_MOVIMIENTO AS EMO ON (EMO.RUT_CODIGO=RUT.RUT_CODIGO)
FULL JOIN SIM_CHEQUEO_PRECIO_ESPECIAL AS CHP ON (CHP.RUT_CODIGO=RUT.RUT_CODIGO)

WHERE
USC.CLI_CODIGO IN (24,84) 