SELECT DISTINCT
        CLI.CLI_NOMBRE,
        PRO.PRO_CODIGO,
        PRO.PRO_NOMBRE,
        MAR.MAR_NOMBRE,
        CAT.CAT_NOMBRE
FROM
        SIM_CLIENTE AS CLI
        JOIN SIM_ACTIVIDAD AS ACT ON ACT.CLI_CODIGO = CLI.CLI_CODIGO AND ACT.ESTADO = 1
        JOIN SIM_PRODUCTO_ACTIVIDAD AS PRA ON PRA.ACT_CODIGO = ACT.ACT_CODIGO AND PRA.ESTADO = 1
        JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO = PRA.PRO_CODIGO
        JOIN SIM_MARCA AS MAR ON MAR.MAR_CODIGO = PRO.MAR_CODIGO AND MAR.ESTADO = 1 AND MAR.MAR_PROPIA = 1
        JOIN SIM_CATEGORIA AS CAT ON CAT.CAT_CODIGO = PRA.CAT_CODIGO
WHERE
        CLI.ESTADO = 1 AND CLI.CLI_CODIGO = 138