WITH SIM_USUARIOS AS(
SELECT
    ACT.CLI_CODIGO,
    ACT.CLI_NOMBRE,
    ACT.ACT_CODIGO,
    ACT.ACT_NOMBRE,
    USU.USU_CODIGO,
    UPPER(USU.USU_NOMBRES + ' ' + USU.USU_APELLIDOS) AS NOMBRE_COMPLETO,
    USU.USU_NUMERO_DOCUMENTO AS #_DOCUEMNTO,
    LOWER(USU.USU_LOGIN) AS LOGIN,
    PER.PER_CODIGO,
    PER.PER_NOMBRE AS PERFIL,
    USC.USC_CODIGO,
    USA.USA_CODIGO,
    PEU.PEU_CODIGO,
    CASE
    WHEN USA.ESTADO=0 AND USC.ESTADO=0 THEN 'CLIANTE-ACTIVIDAD INACTIVO'
    WHEN USC.ESTADO=1 AND USA.ESTADO=0 THEN 'CLIENTE-ACTIVO Y ACTIVIDAD-INACTIVA'
    WHEN USC.ESTADO=0 AND USA.ESTADO=1 THEN 'CLIENTE-INACTIVO Y ACTIVIDAD-ACTIVA'
    WHEN USC.ESTADO=1 AND USA.ESTADO=1 THEN 'ACTIVO'
    ELSE 'HAY NOVEDADES'
    END AS ESTADO
FROM
    SIM_USUARIO AS USU
    LEFT JOIN SIM_USUARIO_CLIENTE AS USC ON USC.USU_CODIGO=USU.USU_CODIGO
    LEFT JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON USA.USC_CODIGO=USC.USC_CODIGO
    LEFT JOIN SIM_PERFIL_USUARIO AS PEU ON PEU.USA_CODIGO=USA.USA_CODIGO AND PEU.ESTADO=1
    LEFT JOIN SIM_PERFIL AS PER ON PER.PER_CODIGO=PEU.PER_CODIGO
    LEFT JOIN (SELECT CLI.CLI_CODIGO,CLI.CLI_NOMBRE,ACT.ACT_CODIGO,ACT.ACT_NOMBRE
                FROM SIM_CLIENTE AS CLI INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.CLI_CODIGO=CLI.CLI_CODIGO) 
                AS ACT ON ACT.ACT_CODIGO=USA.ACT_CODIGO
WHERE
    PEU.PEU_CODIGO IS NOT NULL
)

SELECT DISTINCT
USU.CLI_CODIGO,
USU.CLI_NOMBRE,
USU.ACT_CODIGO,
USU.ACT_NOMBRE,
RUT.PDV_CODIGO,
USU.LOGIN,
REU.ENA_CODIGO,
ENC.ENC_CODIGO,
ENA.ENA_CODIGO,
ENC.ENC_NOMBRE,
REU.REU_CONSECUTIVO_ENC,
RUT.RUT_CODIGO,
RUT.RUT_FECHA_RUTA,
PRG.PRG_CODIGO,
PRG.PRG_PREGUNTA,
REU.RES_CODIGO,
CASE
WHEN RES.RES_RESPUESTA = '' AND REU.REU_OTRO IS NOT NULL THEN REU.REU_OTRO
WHEN RES.RES_RESPUESTA = '' AND REU.REU_OBSERVACION IS NOT NULL THEN REU.REU_OBSERVACION
ELSE RES.RES_RESPUESTA END AS RES_RESPUESTA,
REU.USUARIO_CREACION,
REU.USUARIO_MODIFICACION
FROM
SIM_RUTA AS RUT
INNER JOIN SIM_USUARIOS AS USU ON USU.USA_CODIGO=RUT.USA_CODIGO
INNER JOIN SIM_RESPUESTA_USUARIO AS REU ON REU.RUT_CODIGO=RUT.RUT_CODIGO
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON ENA.ENA_CODIGO=REU.ENA_CODIGO
INNER JOIN SIM_ENCUESTA AS ENC ON ENC.ENC_CODIGO=ENA.ENC_CODIGO
INNER JOIN SIM_RESPUESTA AS RES ON RES.RES_CODIGO=REU.RES_CODIGO
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON PRN.PRN_CODIGO=RES.PRN_CODIGO
INNER JOIN SIM_PREGUNTA AS PRG ON PRG.PRG_CODIGO=PRN.PRG_CODIGO

WHERE
USU.CLI_CODIGO=214