WITH ENCUESTA AS (
SELECT
CLI.CLI_CODIGO,
CLI.CLI_NOMBRE,
ACT.ACT_CODIGO,
ACT.ACT_NOMBRE,
ENC.ENC_CODIGO,
ENA.ENA_CODIGO,
ENC.ENC_NOMBRE,
PRG.PRG_CODIGO,
PRG.PRG_PREGUNTA,
PRN.PRN_CODIGO,
PRN.PRN_ORDEN,
RES.RES_CODIGO,

CASE
WHEN RES.RES_RESPUESTA ='' THEN REU_OBSERVACION
ELSE RES.RES_RESPUESTA
END AS RES_RESPUESTA,

REU.REU_CODIGO,
REU.REU_CONSECUTIVO_ENC,
REU.RUT_CODIGO,
PRG.TIP_CODIGO,
T1.TIP_NOMBRE,
FOA.FOT_CODIGO,
FOT.FOT_RUTA,
REU.USUARIO_CREACION AS USUARIO,
REU.FECHA_CREACION

FROM
SIM_CLIENTE AS CLI
INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.CLI_CODIGO=CLI.CLI_CODIGO
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON ENA.ACT_CODIGO=ACT.ACT_CODIGO
INNER JOIN SIM_ENCUESTA AS ENC ON ENC.ENC_CODIGO=ENA.ENC_CODIGO
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON PRN.ENA_CODIGO=ENA.ENA_CODIGO
INNER JOIN SIM_PREGUNTA AS PRG ON PRG.PRG_CODIGO=PRN.PRG_CODIGO
INNER JOIN SIM_RESPUESTA AS RES ON RES.PRN_CODIGO=PRN.PRN_CODIGO
INNER JOIN SIM_RESPUESTA_USUARIO AS REU ON REU.RES_CODIGO=RES.RES_CODIGO AND REU.ESTADO=1
INNER JOIN SIM_TIPO AS T1 ON T1.TIP_CODIGO=PRG.TIP_CODIGO
LEFT JOIN SIM_FOTO_ASOCIACION AS FOA ON FOA.REU_CODIGO=REU.REU_CODIGO
LEFT JOIN SIM_FOTO AS FOT ON FOT.FOT_CODIGO=FOA.FOT_CODIGO

WHERE
CLI.CLI_CODIGO=212
AND ENA.ENA_CODIGO IN (8208,8212,8248,8209,8211,8250,8210,8213,8249) 
--AND REU.RUT_CODIGO=22698163
)

SELECT
ENC.CLI_CODIGO,
ENC.CLI_NOMBRE,
ENC.ACT_CODIGO,
ENC.ACT_NOMBRE,
ENC.ENC_CODIGO,
ENC.ENA_CODIGO,
ENC.ENC_NOMBRE,
ENC.PRG_CODIGO,
ENC.PRG_PREGUNTA,
IIF (ENC.FOT_RUTA IS NULL,ENC.RES_RESPUESTA,ENC.FOT_RUTA) AS RES_RESPUESTA,
ENC.PRN_CODIGO,
ENC.PRN_ORDEN,
ENC.RES_CODIGO,
ENC.REU_CODIGO,
ENC.REU_CONSECUTIVO_ENC,
ENC.RUT_CODIGO,
ENC.TIP_CODIGO,
ENC.TIP_NOMBRE,
ENC.FOT_CODIGO,
RUT.PDV_CODIGO,
PVC.PVC_NOMBRE_PDV,
RUT.USA_CODIGO,
ENC.USUARIO,
RUT.RUT_FECHA_RUTA

FROM
ENCUESTA AS ENC
LEFT JOIN SIM_RUTA AS RUT ON RUT.RUT_CODIGO=ENC.RUT_CODIGO
LEFT JOIN SIM_PUNTO_VENTA_CLIENTE AS PVC ON PVC.PDV_CODIGO=RUT.PDV_CODIGO AND ENC.ACT_CODIGO=PVC.ACT_CODIGO AND PVC.ESTADO=1

ORDER BY ENC.REU_CODIGO