SELECT DISTINCT

VIS.CLI_CODIGO,
VIS.CLI_NOMBRE,
VIS.ACT_CODIGO,
VIS.ACT_NOMBRE,
VIS.RUT_CODIGO,
PDV.CIU_CODIGO,
PDV.PDV_CODIGO,
PDV.PDV_NOMBRE,
PDV.PDV_DIRECCION,
PDV.PDV_BARRIO,
RUT.RUT_FECHA_RUTA,
USU.USU_LOGIN


FROM
QV_Rutas_Generico_WOW AS VIS
INNER JOIN SIM_PUNTO_VENTA AS PDV ON (PDV.PDV_CODIGO=VIS.PDV_CODIGO)
INNER JOIN SIM_RUTA AS RUT ON (RUT.RUT_CODIGO=VIS.RUT_CODIGO)
INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON (USA.USA_CODIGO=RUT.USA_CODIGO)
INNER JOIN SIM_USUARIO_CLIENTE AS USC ON (USC.USC_CODIGO=USA.USC_CODIGO)
INNER JOIN SIM_USUARIO AS USU ON (USU.USU_CODIGO=USC.USU_CODIGO)


WHERE
CONVERT(DATE,RUT.RUT_FECHA_RUTA) BETWEEN '2024-02-08' AND '2024-02-29'
AND PDV.CIU_CODIGO=4