SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
DECLARE @FECHA_RUT DATE 
SET @FECHA_RUT='2023-01-01' 

SELECT 
RUT.ACT_CODIGO,
RUT.ACT_NOMBRE,
RUT.RUT_CODIGO,
RUT.TIP_CODIGO,
RUT.TIP_NOMBRE,
RUT.USA_CODIGO,
RUT.PDV_CODIGO,
RUT.RUT_FECHA_RUTA,
RUT.USUARIO_MODIFICACION,
RUT.RUT_CODIGO2,
RUT.RUT_FECHA_INICIO_VISITA,
RUT.RUT_FECHA_FIN_VISITA,
IIF(ACO.SIM_ACTIVIDAD_COMERCIAL > 0,1,0) AS SIM_ACTIVIDAD_COMERCIAL,
IIF(AGO.SIM_AGOTADOS>0,1,0) AS SIM_AGOTADOS, 
IIF(AUD.SIM_AUDITORIA>0,1,0) AS SIM_AUDITORIA, 
IIF(CMA.SIM_CAMBIO_MARCA>0,1,0) AS SIM_CAMBIO_MARCA, 
IIF(CAR.SIM_CARAS >0,1,0) AS SIM_CARAS , 
IIF(CPR.SIM_CHEQUEO_PRECIO > 0, 1, 0) AS SIM_CHEQUEO_PRECIO,
IIF(EXI.SIM_EXHIBICION>0,1,0) AS SIM_EXHIBICION, 
IIF(FOT.SIM_FOTO>0,1,0) AS SIM_FOTO, 
IIF(INV.SIM_INVENTARIO>0,1,0) AS SIM_INVENTARIO, 
IIF(NOA.SIM_NOTA>0,1,0) AS SIM_NOTA, 
IIF(REU.SIM_RESPUESTA_USUARIO > 0,1,0) AS SIM_RESPUESTA_USUARIO,
IIF(REV.SIM_RUTERO_VALORIZADO > 0,1,0) AS SIM_RUTERO_VALORIZADO,
IIF(SEV.SIM_SEGUIMIENTO_VENCIMIENTO > 0,1,0) AS SIM_SEGUIMIENTO_VENCIMIENTO,
IIF(TRA.SIM_TRANSFERENCIA > 0, 1, 0) AS SIM_TRANSFERENCIA,
IIF(VEC.SIM_VENCIMIENTO>0,1,0) AS SIM_VENCIMIENTO, 
IIF(VET.SIM_VENTAS >0,1,0) AS SIM_VENTAS , 
IIF(REC.SIM_RECORDATORIO>0,1,0) AS SIM_RECORDATORIO, 
IIF(SER.SIM_SEGUIMIENTO_RECORDATORIO > 0,1,0) AS SIM_SEGUIMIENTO_RECORDATORIO,
IIF(CIT.SIM_CITA>0,1,0) AS SIM_CITA, 
IIF(CAP.SIM_CAPACITACIONES > 0, 1, 0) AS SIM_CAPACITACIONES,
IIF(GEE.SIM_GESTION_EXHIBICION > 0,1,0) AS SIM_GESTION_EXHIBICION,
IIF(EMO.SIM_ENCABEZADO_MOVIMIENTO > 0,1,0) AS SIM_ENCABEZADO_MOVIMIENTO,
IIF(CHP.SIM_CHEQUEO_PRECIO_ESPECIAL > 0,1,0) AS SIM_CHEQUEO_PRECIO_ESPECIAL,
IIF(ACO.SIM_ACTIVIDAD_COMERCIAL > 0,1,0) + IIF(AGO.SIM_AGOTADOS > 0, 1, 0) + IIF(AUD.SIM_AUDITORIA > 0,1,0) + IIF(CMA.SIM_CAMBIO_MARCA > 0, 1, 0) + IIF(CAR.SIM_CARAS > 0, 1, 0) + IIF(CPR.SIM_CHEQUEO_PRECIO > 0, 1, 0) + IIF(EXI.SIM_EXHIBICION > 0, 1, 0) + IIF(FOT.SIM_FOTO > 0, 1, 0) + IIF(INV.SIM_INVENTARIO > 0, 1, 0) + IIF(NOA.SIM_NOTA > 0, 1, 0) + IIF(REU.SIM_RESPUESTA_USUARIO > 0,1,0) +IIF(REV.SIM_RUTERO_VALORIZADO > 0,1,0) + IIF(SEV.SIM_SEGUIMIENTO_VENCIMIENTO > 0,1,0) + IIF(TRA.SIM_TRANSFERENCIA > 0, 1, 0) + IIF(VEC.SIM_VENCIMIENTO > 0, 1, 0) + IIF(VET.SIM_VENTAS > 0, 1, 0) +IIF(REC.SIM_RECORDATORIO > 0, 1, 0) + IIF(SER.SIM_SEGUIMIENTO_RECORDATORIO > 0,1,0) + IIF(CIT.SIM_CITA > 0, 1, 0) + IIF(CAP.SIM_CAPACITACIONES > 0, 1, 0) + IIF(GEE.SIM_GESTION_EXHIBICION > 0,1,0) + IIF(EMO.SIM_ENCABEZADO_MOVIMIENTO > 0,1,0) AS CAPTURA 

FROM 
(
SELECT 
ACT.ACT_CODIGO, 
ACT.ACT_NOMBRE, 
R.RUT_CODIGO, 
R.TIP_CODIGO, 
T.TIP_NOMBRE, 
R.USA_CODIGO, 
R.PDV_CODIGO, 
R.RUT_FECHA_RUTA, 
R.USUARIO_MODIFICACION, 
R.RUT_CODIGO2, 
R.RUT_FECHA_INICIO_VISITA, 
R.RUT_FECHA_FIN_VISITA 
FROM 
SIM_RUTA AS R 
INNER JOIN SIM_TIPO AS T ON ( R.TIP_CODIGO=T.TIP_CODIGO) 
INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON (USA.USA_CODIGO=R.USA_CODIGO) 
INNER JOIN SIM_ACTIVIDAD AS ACT ON (USA.ACT_CODIGO=ACT.ACT_CODIGO) 
WHERE 
CONVERT(DATE,RUT_FECHA_RUTA) >= @FECHA_RUT AND R.ESTADO=1) AS RUT 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_ACTIVIDAD_COMERCIAL' 
FROM SIM_ACTIVIDAD_COMERCIAL 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS ACO ON (RUT.RUT_CODIGO=ACO.SIM_ACTIVIDAD_COMERCIAL) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_AGOTADOS' 
FROM SIM_AGOTADOS 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS AGO ON (RUT.RUT_CODIGO=AGO.SIM_AGOTADOS) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_AUDITORIA' 
FROM SIM_AUDITORIA 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS AUD ON (RUT.RUT_CODIGO=AUD.SIM_AUDITORIA) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_CAMBIO_MARCA' 
FROM SIM_CAMBIO_MARCA 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS CMA ON (RUT.RUT_CODIGO=CMA.SIM_CAMBIO_MARCA) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_CARAS ' 
FROM SIM_CARAS 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS CAR ON (RUT.RUT_CODIGO=CAR.SIM_CARAS) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_CHEQUEO_PRECIO' 
FROM SIM_CHEQUEO_PRECIO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS CPR ON 
(RUT.RUT_CODIGO=CPR.SIM_CHEQUEO_PRECIO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_EXHIBICION' 
FROM SIM_EXHIBICION 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS EXI ON (RUT.RUT_CODIGO=EXI.SIM_EXHIBICION) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_FOTO' 
FROM SIM_FOTO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS FOT ON (RUT.RUT_CODIGO=FOT.SIM_FOTO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_INVENTARIO' 
FROM SIM_INVENTARIO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS INV ON (RUT.RUT_CODIGO=INV.SIM_INVENTARIO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_NOTA' 
FROM SIM_NOTA 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS NOA ON (RUT.RUT_CODIGO=NOA.SIM_NOTA) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_RESPUESTA_USUARIO' 
FROM SIM_RESPUESTA_USUARIO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS REU ON ( RUT.RUT_CODIGO=REU.SIM_RESPUESTA_USUARIO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_RUTERO_VALORIZADO' 
FROM SIM_RUTERO_VALORIZADO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS REV ON (RUT.RUT_CODIGO=REV.SIM_RUTERO_VALORIZADO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_SEGUIMIENTO_VENCIMIENTO' 
FROM SIM_SEGUIMIENTO_VENCIMIENTO WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS SEV ON (RUT.RUT_CODIGO=SEV.SIM_SEGUIMIENTO_VENCIMIENTO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_TRANSFERENCIA' 
FROM SIM_TRANSFERENCIA 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS TRA ON (RUT.RUT_CODIGO=TRA.SIM_TRANSFERENCIA) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_VENCIMIENTO' 
FROM SIM_VENCIMIENTO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS VEC ON (RUT.RUT_CODIGO=VEC.SIM_VENCIMIENTO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_VENTAS ' 
FROM SIM_VENTAS 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS VET ON (RUT.RUT_CODIGO=VET.SIM_VENTAS) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_RECORDATORIO' 
FROM SIM_RECORDATORIO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS REC ON (RUT.RUT_CODIGO=REC.SIM_RECORDATORIO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_SEGUIMIENTO_RECORDATORIO' 
FROM SIM_SEGUIMIENTO_RECORDATORIO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS SER ON (RUT.RUT_CODIGO=SER.SIM_SEGUIMIENTO_RECORDATORIO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_CITA' 
FROM SIM_CITA 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS CIT ON (RUT.RUT_CODIGO=CIT.SIM_CITA) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_CAPACITACIONES' 
FROM SIM_CAPACITACIONES 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS CAP ON (RUT.RUT_CODIGO=CAP.SIM_CAPACITACIONES) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_GESTION_EXHIBICION' 
FROM SIM_GESTION_EXHIBICION 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS GEE ON (RUT.RUT_CODIGO=GEE.SIM_GESTION_EXHIBICION) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_ENCABEZADO_MOVIMIENTO' 
FROM SIM_ENCABEZADO_MOVIMIENTO 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS EMO ON (RUT.RUT_CODIGO=EMO.SIM_ENCABEZADO_MOVIMIENTO) 

FULL JOIN 

(SELECT DISTINCT RUT_CODIGO AS 'SIM_CHEQUEO_PRECIO_ESPECIAL' 
FROM SIM_CHEQUEO_PRECIO_ESPECIAL 
WHERE FECHA_CREACION >= @FECHA_RUT AND ESTADO=1) AS CHP ON (RUT.RUT_CODIGO=CHP.SIM_CHEQUEO_PRECIO_ESPECIAL)

WHERE 
--RUT.TIP_CODIGO=30
--USA_CODIGO=47791
--AND PDV_CODIGO IN (13069)
--RUT.RUT_CODIGO IN (20386637)

GROUP BY 
RUT.ACT_CODIGO, RUT.ACT_NOMBRE, RUT.RUT_CODIGO, RUT.TIP_CODIGO, RUT.TIP_NOMBRE, RUT.USA_CODIGO, RUT.PDV_CODIGO, RUT.RUT_FECHA_RUTA, RUT.USUARIO_MODIFICACION, RUT.RUT_CODIGO2, RUT.RUT_FECHA_INICIO_VISITA, RUT.RUT_FECHA_FIN_VISITA, ACO.SIM_ACTIVIDAD_COMERCIAL, AGO.SIM_AGOTADOS, AUD.SIM_AUDITORIA, CMA.SIM_CAMBIO_MARCA, CAR.SIM_CARAS , CPR.SIM_CHEQUEO_PRECIO, EXI.SIM_EXHIBICION, FOT.SIM_FOTO, INV.SIM_INVENTARIO, NOA.SIM_NOTA, REU.SIM_RESPUESTA_USUARIO, REV.SIM_RUTERO_VALORIZADO, SEV.SIM_SEGUIMIENTO_VENCIMIENTO, TRA.SIM_TRANSFERENCIA, VEC.SIM_VENCIMIENTO, VET.SIM_VENTAS , REC.SIM_RECORDATORIO, SER.SIM_SEGUIMIENTO_RECORDATORIO, CIT.SIM_CITA, CAP.SIM_CAPACITACIONES, GEE.SIM_GESTION_EXHIBICION, EMO.SIM_ENCABEZADO_MOVIMIENTO, CHP.SIM_CHEQUEO_PRECIO_ESPECIAL

HAVING
 (
 IIF(ACO.SIM_ACTIVIDAD_COMERCIAL>0,1,0) + IIF(AGO.SIM_AGOTADOS>0,1,0) + IIF(AUD.SIM_AUDITORIA>0,1,0) + IIF(CMA.SIM_CAMBIO_MARCA>0,1,0) + IIF(CAR.SIM_CARAS >0,1,0) +IIF(CPR.SIM_CHEQUEO_PRECIO>0,1,0) + IIF(EXI.SIM_EXHIBICION>0,1,0) + IIF(FOT.SIM_FOTO>0,1,0) + IIF(INV.SIM_INVENTARIO>0,1,0) + IIF(NOA.SIM_NOTA>0,1,0) + IIF(REU.SIM_RESPUESTA_USUARIO>0,1,0) + IIF(REV.SIM_RUTERO_VALORIZADO>0,1,0) + IIF(SEV.SIM_SEGUIMIENTO_VENCIMIENTO>0,1,0) + IIF(TRA.SIM_TRANSFERENCIA>0,1,0) + IIF(VEC.SIM_VENCIMIENTO>0,1,0) + IIF(VET.SIM_VENTAS >0,1,0) + IIF(REC.SIM_RECORDATORIO>0,1,0) + IIF(SER.SIM_SEGUIMIENTO_RECORDATORIO>0,1,0) + IIF(CIT.SIM_CITA>0,1,0) + IIF(CAP.SIM_CAPACITACIONES>0,1,0) + IIF(GEE.SIM_GESTION_EXHIBICION>0,1,0) + IIF(EMO.SIM_ENCABEZADO_MOVIMIENTO>0,1,0) + IIF(CHP.SIM_CHEQUEO_PRECIO_ESPECIAL>0,1,0)
 )> 0
 
ORDER BY RUT_CODIGO 