SELECT DISTINCT
    CLI.CLI_CODIGO,
    CLI.CLI_NOMBRE,
    ACT.ACT_CODIGO,
    ACT.ACT_NOMBRE,
    USU.USU_NUMERO_DOCUMENTO AS DOCUMENTO,
    USU.USU_NOMBRES + ' ' + USU.USU_APELLIDOS AS NOMBRE_COMPLETO,
    USU.USU_LOGIN,
    PER.PER_CODIGO,
    PER.PER_NOMBRE,
    USU.USU_CODIGO,
    USC.USC_CODIGO,
    USA.USA_CODIGO,
    ACT.ESTADO AS ESTADO_ACT,
    CLI.ESTADO AS ESTADO_CLI,
    USU.ESTADO AS ESTADO_USU,
    USC.ESTADO AS ESTADO_USC,
    USA.ESTADO AS ESTADO_USA,
    PEU.ESTADO AS ESTADO_PER,
    UAE.UAE_CODIGO,
    UAE.TIP_CODIGO AS TIP_CARGO,
    TIP2.TIP_NOMBRE AS TIP_CARGO_CARGO,
    USU2.USU_NUMERO_DOCUMENTO AS DOCUMENTO_JEFE,
    USU2.USU_NOMBRES + ' ' + USU2.USU_APELLIDOS AS NOMBRE_COMPLETO_JEFE,
    USU2.USU_LOGIN AS USU_LOGIN_JEFE,
    PER2.PER_CODIGO AS PER_CODIGO_JEFE,
    PER2.PER_NOMBRE AS PER_NOMBRE_JEFE,
    USU2.USU_CODIGO AS USU_CODIGO_JEFE,
    USC2.USC_CODIGO AS USC_CODIGO_JEFE,
    USA2.USA_CODIGO AS USA_CODIGO_JEFE,
    UAE.ESTADO AS ESTADO_UAE_JEFE,
    USU2.ESTADO AS ESTADO_USU_JEFE
    
FROM dbo.SIM_USUARIO AS USU WITH (NOLOCK)
INNER JOIN dbo.SIM_USUARIO_CLIENTE AS USC WITH (NOLOCK) ON USU.USU_CODIGO = USC.USU_CODIGO
INNER JOIN dbo.SIM_USUARIO_ACTIVIIDAD AS USA WITH (NOLOCK) ON USA.USC_CODIGO = USC.USC_CODIGO
INNER JOIN dbo.SIM_PERFIL_USUARIO AS PEU WITH (NOLOCK) ON PEU.USA_CODIGO = USA.USA_CODIGO
INNER JOIN dbo.SIM_PERFIL AS PER WITH (NOLOCK) ON PER.PER_CODIGO = PEU.PER_CODIGO
INNER JOIN dbo.SIM_ACTIVIDAD AS ACT WITH (NOLOCK) ON ACT.ACT_CODIGO = USA.ACT_CODIGO
INNER JOIN dbo.SIM_CLIENTE AS CLI WITH (NOLOCK) ON CLI.CLI_CODIGO = ACT.CLI_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO_ACTIVIDAD_ENCARGADO AS UAE WITH (NOLOCK) ON UAE.USA_CODIGO2 = USA.USA_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO_ACTIVIIDAD AS USA2 WITH (NOLOCK) ON UAE.USA_CODIGO = USA2.USA_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO_CLIENTE AS USC2 WITH (NOLOCK) ON USA2.USC_CODIGO = USC2.USC_CODIGO 
FULL OUTER JOIN dbo.SIM_USUARIO AS USU2 WITH (NOLOCK) ON USU2.USU_CODIGO = USC2.USU_CODIGO 
FULL OUTER JOIN dbo.SIM_PERFIL_USUARIO AS PEU2 WITH (NOLOCK) ON PEU2.USA_CODIGO = USA2.USA_CODIGO 
FULL OUTER JOIN dbo.SIM_PERFIL AS PER2 WITH (NOLOCK) ON PER2.PER_CODIGO = PEU2.PER_CODIGO 
FULL OUTER JOIN dbo.SIM_TIPO AS TIP2 WITH (NOLOCK) ON TIP2.TIP_CODIGO = UAE.TIP_CODIGO

WHERE
USU.ESTADO = 1 AND USA.ESTADO=1 AND (UAE.ESTADO=1 OR UAE.ESTADO IS NULL)

ORDER BY
    CLI.CLI_CODIGO,
    ACT.ACT_CODIGO,
    PER.PER_NOMBRE,
    USU.USU_CODIGO,
    USC.USC_CODIGO,
    USA.USA_CODIGO;