WITH CLI_ACT AS (
        SELECT
            CLI.CLI_CODIGO,CLI.CLI_NOMBRE,ACT.ACT_CODIGO,ACT.ACT_NOMBRE
        FROM SIM_CLIENTE AS CLI INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.CLI_CODIGO=CLI.CLI_CODIGO
),
JEFE AS (
        SELECT
            USU.USU_CODIGO,
            UPPER(USU.USU_NOMBRES + ' ' + USU.USU_APELLIDOS) AS NOMBRE_JEFE,
            USU.USU_NUMERO_DOCUMENTO AS #_DOCUEMNTO_JEFE,
            LOWER(USU.USU_LOGIN) AS LOGIN_JEFE,
            UAE.UAE_CODIGO,
            UAE.USA_CODIGO AS USA_JEFE,
            UAE.USA_CODIGO2 AS USA_MERCADERISTA,
            UAE.TIP_CODIGO AS TIP_CARGO,
            TIP.TIP_NOMBRE AS CARGO
        FROM
            SIM_USUARIO_ACTIVIDAD_ENCARGADO AS UAE
            LEFT JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON USA.USA_CODIGO=UAE.USA_CODIGO
            LEFT JOIN SIM_USUARIO_CLIENTE AS USC ON USC.USC_CODIGO=USA.USC_CODIGO
            LEFT JOIN SIM_USUARIO AS USU ON USU.USU_CODIGO=USC.USU_CODIGO
            INNER JOIN SIM_TIPO AS TIP ON TIP.TIP_CODIGO=UAE.TIP_CODIGO
        WHERE
            UAE.ESTADO=1)
SELECT
    ACT.CLI_CODIGO,
    ACT.CLI_NOMBRE,
    ACT.ACT_CODIGO,
    ACT.ACT_NOMBRE,
    USU.USU_CODIGO,
    UPPER(USU.USU_NOMBRES + ' ' + USU.USU_APELLIDOS) AS NOMBRE_COMPLETO,
    USU.USU_NUMERO_DOCUMENTO AS #_DOCUEMNTO,
    LOWER(USU.USU_LOGIN) AS LOGIN,
    PER.PER_CODIGO,
    PER.PER_NOMBRE AS PERFIL,
    USC.USC_CODIGO,
    USA.USA_CODIGO,
    PEU.PEU_CODIGO,
    UAE_CODIGO,
    TIP_CARGO,
    CARGO
    NOMBRE_JEFE,
    LOGIN_JEFE,
    USA_JEFE,
    CASE
    WHEN USA.ESTADO=0 AND USC.ESTADO=0 THEN 'CLIANTE-ACTIVIDAD INACTIVO'
    WHEN USC.ESTADO=1 AND USA.ESTADO=0 THEN 'CLIENTE-ACTIVO Y ACTIVIDAD-INACTIVA'
    WHEN USC.ESTADO=0 AND USA.ESTADO=1 THEN 'CLIENTE-INACTIVO Y ACTIVIDAD-ACTIVA'
    WHEN USC.ESTADO=1 AND USA.ESTADO=1 THEN 'ACTIVO'
    ELSE 'HAY NOVEDADES'
    END AS ESTADO
FROM
    SIM_USUARIO AS USU
    LEFT JOIN SIM_USUARIO_CLIENTE AS USC ON USC.USU_CODIGO=USU.USU_CODIGO
    LEFT JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON USA.USC_CODIGO=USC.USC_CODIGO
    LEFT JOIN SIM_PERFIL_USUARIO AS PEU ON PEU.USA_CODIGO=USA.USA_CODIGO AND PEU.ESTADO=1
    LEFT JOIN SIM_PERFIL AS PER ON PER.PER_CODIGO=PEU.PER_CODIGO
    LEFT JOIN CLI_ACT AS ACT ON ACT.ACT_CODIGO=USA.ACT_CODIGO
    LEFT JOIN JEFE AS JEF ON JEF.USA_MERCADERISTA=USA.USA_CODIGO
WHERE
    USU.ESTADO=1 AND PEU.PEU_CODIGO IS NOT NULL
    AND ACT.CLI_CODIGO=108
ORDER BY
    ACT.CLI_CODIGO,ACT.ACT_CODIGO,PER.PER_CODIGO,USU.USU_CODIGO