SELECT

PDV.PDV_CODIGO,
PDV.CIU_CODIGO,
CIU.CIU_NOMBRE,
PDV.TIP_CODIGO,
T1.TIP_NOMBRE,
PDV.PDV_NOMBRE,
PDV.PDV_DIRECCION,
PDV.PDV_BARRIO,
PDV.TIP_CODIGO2,
T2.TIP_NOMBRE

FROM
SIM_PUNTO_VENTA AS PDV
INNER JOIN SIM_TIPO AS T1 ON (T1.TIP_CODIGO=PDV.TIP_CODIGO)
INNER JOIN SIM_TIPO AS T2 ON (T2.TIP_CODIGO=PDV.TIP_CODIGO2)
INNER JOIN SIM_CIUDAD AS CIU ON (CIU.CIU_CODIGO=PDV.CIU_CODIGO)
INNER JOIN SIM_DEPARTAMENTO AS DEP ON (DEP.DEP_CODIGO=CIU.DEP_CODIGO)
INNER JOIN SIM_PAIS AS PAI ON (PAI.PAI_CODIGO=DEP.PAI_CODIGO AND PAI.PAI_CODIGO=1)
WHERE
PDV.ESTADO=1 AND
(PDV.TIP_CODIGO NOT IN (39995,39996,9594,42084,42112,14634,28875,1511,14012,9593,42085,14635,42113,39688,54286) 
AND PDV.TIP_CODIGO2 NOT IN (39995,39996,9594,42084,42112,14634,28875,1511,14012,9593,42085,14635,42113,10304))
AND (
(PDV.PDV_DIRECCION LIKE '%CR 7 # 7-30%' AND CIU.CIU_CODIGO=963 AND PDV.ESTADO=1)
)

// CODIGO EXCEL //
=CONCAT("OR(PDV.PDV_DIRECCION LIKE '";J2;"' AND CIU.CIU_CODIGO=";B2;" AND PDV.ESTADO=1)")

=CONCAT("INSERT INTO SIM_PUNTO_VENTA (CIU_CODIGO, ";"TIP_CODIGO, ";"PDV_NOMBRE, ";"PDV_NOMBRE_CORTO, ";"PDV_NUMERO_DOCUMENTO, ";"PDV_DIRECCION, ";"PDV_BARRIO, ";"PDV_TELEFONO1, ";"PDV_TELEFONO2, ";"PDV_ADMINISTRADOR1, ";"PDV_ADMINISTRADOR2, ";"PDV_LATITUD, ";"PDV_LONGITD, ";"PDV_DEPENDIENTE, ";"USUARIO_CREACION, ";"FECHA_CREACION, ";"USUARIO_MODIFICACION, ";"FECHA_MODIFICACION, ";"ESTADO, ";"TIP_CODIGO2, ";"PDV_CODIGO_CADENA, ";"PDV_CODIGO_COPIDROGAS, ";"PDV_CODIGO_ISM, ";"PDV_CODIGO_EAN, ";"PDV_CODIGO_NIELSEN, ";"PDV_CODIGO_CEM, ";"PDV_CODIGO_BRIEF, ";"PDV_CODIGO_SAP, ";"PDV_MOTIVO_BAJA, ";"TIP_CODIGO3) VALUES (";B2;",";D2;",'";H2;"','";IZQUIERDA(H2;50);"',";SI(I2="";"null";CONCAT("'";I2;"'"));",'";J2;"',";SI(K2="";"''";CONCAT("'";K2;"'"));",";SI(L2="";"''";CONCAT("'";L2;"'"));",";SI(M2="";"''";CONCAT("'";M2;"'"));",";SI(N2="";"''";CONCAT("'";N2;"'"));",";SI(O2="";"''";CONCAT("'";O2;"'"));",";SI(P2="";"null";CONCAT("'";P2;"'"));",";SI(Q2="";"null";CONCAT("'";Q2;"'"));",null,'carlos.rgaitan 31798' ,GETDATE(),'carlos.rgaitan 31798' ,GETDATE(),1,";F2;",null,null,null,null,null,null,null,null,null,null)")