SELECT

CLI.CLI_CODIGO,
CLI.CLI_NOMBRE,
ENA.ACT_CODIGO,
ACT.ACT_NOMBRE,
ENC.ENC_CODIGO,
ENC.ENC_NOMBRE,
ENA.ENA_CODIGO,
ENC.ENCUESTA_OBLIGATORIA,
ENA.ENA_ENCUESTA_MULTIPLE,

CASE
WHEN ENA.TIP_CODIGO1 IS NOT NULL THEN ENA.TIP_CODIGO1
WHEN ENA.TIP_CODIGO2 IS NOT NULL THEN ENA.TIP_CODIGO2
WHEN ENA.TIP_CODIGO3 IS NOT NULL THEN ENA.TIP_CODIGO3
WHEN ENA.TIP_CODIGO4 IS NOT NULL THEN ENA.TIP_CODIGO4
ELSE NULL END AS TIP_CODIGO_PDV,

CASE
WHEN ENA.TIP_CODIGO1 IS NOT NULL THEN TIP_1.TIP_NOMBRE
WHEN ENA.TIP_CODIGO2 IS NOT NULL THEN TIP_2.TIP_NOMBRE
WHEN ENA.TIP_CODIGO3 IS NOT NULL THEN TIP_3.TIP_NOMBRE
WHEN ENA.TIP_CODIGO4 IS NOT NULL THEN TIP_4.TIP_NOMBRE
ELSE NULL END AS TIP_NOMBRE_PDV,

PRN.PRG_CODIGO,
PRG.PRG_PREGUNTA,
PRG.TIP_CODIGO,
TIP1.TIP_NOMBRE,
PRN.PRN_CODIGO,
PRN.PRN_ORDEN AS NUMERO_PREGUNRA,
PRN_2.PRN_ORDEN AS SALTAR_A_PREGUNTA,
RES.RES_CODIGO,
RES.RES_RESPUESTA,
RES.TIP_CODIGO,
TIP2.TIP_NOMBRE,
RES.RES_ORDEN AS ORDEN_RESPUESTA,
RES.RES_PUNTUACION

FROM
SIM_ENCUESTA AS ENC
INNER JOIN SIM_ENCUASTA_ACTIVIIDAD AS ENA ON (ENC.ENC_CODIGO=ENA.ENC_CODIGO)
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=ENA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (ACT.CLI_CODIGO=CLI.CLI_CODIGO)
INNER JOIN SIM_PREGUNTA_ENCUESTA AS PRN ON (PRN.ENA_CODIGO=ENA.ENA_CODIGO)
INNER JOIN SIM_PREGUNTA AS PRG ON (PRG.PRG_CODIGO=PRN.PRG_CODIGO)
INNER JOIN SIM_RESPUESTA AS RES ON (RES.PRN_CODIGO=PRN.PRN_CODIGO)
INNER JOIN SIM_TIPO AS TIP1 ON (TIP1.TIP_CODIGO=PRG.TIP_CODIGO)
INNER JOIN SIM_TIPO AS TIP2 ON (TIP2.TIP_CODIGO=RES.TIP_CODIGO)
FULL JOIN SIM_TIPO AS TIP_1 ON (TIP_1.TIP_CODIGO=ENA.TIP_CODIGO1)
FULL JOIN SIM_TIPO AS TIP_2 ON (TIP_2.TIP_CODIGO=ENA.TIP_CODIGO2)
FULL JOIN SIM_TIPO AS TIP_3 ON (TIP_3.TIP_CODIGO=ENA.TIP_CODIGO3)
FULL JOIN SIM_TIPO AS TIP_4 ON (TIP_4.TIP_CODIGO=ENA.TIP_CODIGO4)
FULL JOIN SIM_PREGUNTA_ENCUESTA AS PRN_2 ON (RES.RES_SALTAR_A=PRN_2.PRN_CODIGO)

WHERE
ENC.ESTADO=1 AND ENA.ESTADO=1 AND ACT.ESTADO=1 AND CLI.ESTADO=1 AND PRG.ESTADO=1 AND PRN.ESTADO=1 AND RES.ESTADO=1

ORDER BY CLI.CLI_CODIGO, ACT.ACT_CODIGO, ENA.ENA_CODIGO, PRN.PRN_ORDEN, RES.RES_ORDEN