WITH USUARIOS AS(
    SELECT
        CLI.CLI_CODIGO,
        CLI.CLI_NOMBRE,
        ACT.ACT_CODIGO,
        ACT.ACT_NOMBRE,
        USU.USU_CODIGO,
        UPPER(USU.USU_NOMBRES + ' ' + USU.USU_APELLIDOS) AS NOMBRE_COMPLETO,
        USU.USU_NUMERO_DOCUMENTO AS #_DOCUEMNTO,
        LOWER(USU.USU_LOGIN) AS LOGIN,
        PER.PER_CODIGO,
        PER.PER_NOMBRE AS PERFIL,
        USC.USC_CODIGO,
        USA.USA_CODIGO,
        PEU.PEU_CODIGO,
        CASE
        WHEN USA.ESTADO=0 AND USC.ESTADO=0 THEN 'CLIANTE-ACTIVIDAD INACTIVO'
        WHEN USC.ESTADO=1 AND USA.ESTADO=0 THEN 'CLIENTE-ACTIVO Y ACTIVIDAD-INACTIVA'
        WHEN USC.ESTADO=0 AND USA.ESTADO=1 THEN 'CLIENTE-INACTIVO Y ACTIVIDAD-ACTIVA'
        WHEN USC.ESTADO=1 AND USA.ESTADO=1 THEN 'ACTIVO'
        ELSE 'HAY NOVEDADES'
        END AS ESTADO
    FROM
        SIM_USUARIO AS USU
        LEFT JOIN SIM_USUARIO_CLIENTE AS USC ON USC.USU_CODIGO=USU.USU_CODIGO
        LEFT JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON USA.USC_CODIGO=USC.USC_CODIGO
        LEFT JOIN SIM_PERFIL_USUARIO AS PEU ON PEU.USA_CODIGO=USA.USA_CODIGO AND PEU.ESTADO=1
        LEFT JOIN SIM_PERFIL AS PER ON PER.PER_CODIGO=PEU.PER_CODIGO
        LEFT JOIN SIM_ACTIVIDAD AS ACT ON ACT.ACT_CODIGO=USA.ACT_CODIGO
        LEFT JOIN SIM_CLIENTE AS CLI ON ACT.CLI_CODIGO=CLI.CLI_CODIGO
    WHERE
        USU.ESTADO=1 AND PEU.PEU_CODIGO IS NOT NULL
        AND ACT.CLI_CODIGO>0),
PUNTOS AS (
    SELECT DISTINCT
        YEAR(RUT_FECHA_RUTA) AS AÑO,
        MONTH(RUT_FECHA_RUTA) AS MES,
        CLI.CLI_CODIGO,
        COUNT(DISTINCT RUT.PDV_CODIGO) AS #_PDV,
        COUNT(DISTINCT RUT.USA_CODIGO) AS #_USUARIOS
    FROM
    SIM_ACTIVIDAD AS ACT
        INNER JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON USA.ACT_CODIGO=ACT.ACT_CODIGO AND ACT.ESTADO=1
        INNER JOIN SIM_RUTA AS RUT ON RUT.USA_CODIGO=USA.USA_CODIGO AND RUT.TIP_CODIGO=32
        INNER JOIN SIM_CLIENTE AS CLI ON CLI.CLI_CODIGO=ACT.CLI_CODIGO AND CLI.ESTADO=1
    WHERE
        CLI.CLI_CODIGO>=0 AND YEAR(RUT.RUT_FECHA_RUTA)>=2023
    GROUP BY 
        CLI.CLI_CODIGO,YEAR(RUT_FECHA_RUTA), MONTH(RUT_FECHA_RUTA)),
PRODUCTOS AS (
    SELECT DISTINCT
        YEAR(RUT.RUT_FECHA_RUTA) AS AÑO,
        MONTH(RUT.RUT_FECHA_RUTA) AS MES,
        CLI.CLI_CODIGO,
        COUNT(DISTINCT MDO.PRO_CODIGO) AS #_SKU,
        COUNT(DISTINCT MDO.MAR_CODIGO) AS #_MARCA
    FROM
        SIM_ACCION_ACTIVIDAD AS ACA
        INNER JOIN SIM_ENCABEZADO_PARRILLA AS ENP ON ENP.ACA_CODIGO=ACA.ACA_CODIGO
        INNER JOIN (
            SELECT 'SIM_AGOTADOS' AS MODULO, AGO_CODIGO, RUT_CODIGO AS PKEY, RUT_CODIGO, M.FECHA_CREACION, M.ENP_CODIGO, M.PRO_CODIGO, PRO.MAR_CODIGO FROM SIM_AGOTADOS AS M INNER JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO=M.PRO_CODIGO
            UNION
            SELECT 'SIM_AUDITORIA', AUD_CODIGO, RUT_CODIGO, RUT_CODIGO, M.FECHA_CREACION, M.ENP_CODIGO, M.PRO_CODIGO, PRO.MAR_CODIGO FROM  SIM_AUDITORIA AS M INNER JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO=M.PRO_CODIGO
            UNION 
            SELECT 'SIM_CHEQUEO_PRECIO', CHP_CODIGO, RUT_CODIGO, RUT_CODIGO, M.FECHA_CREACION, M.ENP_CODIGO, M.PRO_CODIGO, PRO.MAR_CODIGO FROM  SIM_CHEQUEO_PRECIO AS M INNER JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO=M.PRO_CODIGO
            UNION 
            SELECT 'SIM_CHEQUEO_PRECIO_ESPECIAL', CPE_CODIGO, RUT_CODIGO, RUT_CODIGO, M.FECHA_CREACION, M.ENP_CODIGO, M.PRO_CODIGO, PRO.MAR_CODIGO FROM  SIM_CHEQUEO_PRECIO_ESPECIAL AS M INNER JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO=M.PRO_CODIGO
            UNION 
            SELECT 'SIM_INVENTARIO', INV_CODIGO, RUT_CODIGO, RUT_CODIGO, M.FECHA_CREACION, M.ENP_CODIGO, M.PRO_CODIGO, PRO.MAR_CODIGO FROM  SIM_INVENTARIO AS M INNER JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO=M.PRO_CODIGO
            UNION 
            SELECT 'SIM_VENTAS', VEN_CODIGO, RUT_CODIGO, RUT_CODIGO, M.FECHA_CREACION, M.ENP_CODIGO, M.PRO_CODIGO, PRO.MAR_CODIGO FROM  SIM_VENTAS AS M INNER JOIN SIM_PRODUCTO AS PRO ON PRO.PRO_CODIGO=M.PRO_CODIGO
            ) AS MDO ON MDO.ENP_CODIGO=ENP.ENP_CODIGO
        INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.ACT_CODIGO=ACA.ACT_CODIGO AND ACT.ESTADO=1
        INNER JOIN SIM_CLIENTE AS CLI ON CLI.CLI_CODIGO=ACT.CLI_CODIGO AND CLI.ESTADO=1
        INNER JOIN SIM_RUTA AS RUT ON RUT.RUT_CODIGO=MDO.RUT_CODIGO
    WHERE 
        CLI.CLI_CODIGO>=0 AND YEAR(RUT.RUT_FECHA_RUTA)>=2023
    GROUP BY 
        CLI.CLI_CODIGO,YEAR(RUT_FECHA_RUTA), MONTH(RUT_FECHA_RUTA)),
MODULOS AS (
    SELECT * FROM (
        SELECT DISTINCT
            YEAR(RUT.RUT_FECHA_RUTA) AS AÑO,
            MONTH(RUT.RUT_FECHA_RUTA) AS MES,
            CLI.CLI_CODIGO,
            CLI.CLI_NOMBRE, 
            MDU.MODULO,
            COUNT(MDU.RUT_CODIGO) OVER(PARTITION BY CLI.CLI_CODIGO, YEAR(RUT.RUT_FECHA_RUTA), MONTH(RUT.RUT_FECHA_RUTA), MDU.MODULO) AS NUMERO_REGISTROS
        FROM
            SIM_USUARIO_ACTIVIIDAD AS USA
            INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.ACT_CODIGO = USA.ACT_CODIGO AND ACT.ESTADO=1
            INNER JOIN SIM_CLIENTE AS CLI ON CLI.CLI_CODIGO = ACT.CLI_CODIGO AND CLI.ESTADO=1
            INNER JOIN SIM_USUARIO_CLIENTE AS USC ON USC.USC_CODIGO = USA.USC_CODIGO
            INNER JOIN SIM_RUTA AS RUT ON RUT.USA_CODIGO = USA.USA_CODIGO AND RUT.TIP_CODIGO=32
            INNER JOIN (
                SELECT 'SIM_RUTA' AS MODULO, RUT_CODIGO AS PKEY, RUT_CODIGO, FECHA_CREACION FROM SIM_RUTA 
                UNION 
                SELECT 'SIM_ACOMPANANTE', ACP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ACOMPANANTE
                UNION 
                SELECT 'SIM_ACTIVIDAD_COMERCIAL', ACO_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ACTIVIDAD_COMERCIAL
                UNION 
                SELECT 'SIM_AGOTADOS', AGO_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_AGOTADOS
                UNION 
                SELECT 'SIM_ASISTENCIA', ASI_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ASISTENCIA
                UNION 
                SELECT 'SIM_AUDITORIA', AUD_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_AUDITORIA
                UNION 
                SELECT 'SIM_CAMBIO_MARCA', CAM_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CAMBIO_MARCA
                UNION 
                SELECT 'SIM_CAMBIO_PRODUCTO', CAP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CAMBIO_PRODUCTO
                UNION 
                SELECT 'SIM_CAPACITACIONES', CAP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CAPACITACIONES
                UNION 
                SELECT 'SIM_CARAS', CAR_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CARAS
                UNION 
                SELECT 'SIM_CHEQUEO_PRECIO', CHP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CHEQUEO_PRECIO
                UNION 
                SELECT 'SIM_CHEQUEO_PRECIO_ESPECIAL', CPE_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CHEQUEO_PRECIO_ESPECIAL
                UNION 
                SELECT 'SIM_CITA', CIT_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CITA
                UNION 
                SELECT 'SIM_ENCABEZADO_MOVIMIENTO', ENM_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ENCABEZADO_MOVIMIENTO
                UNION 
                SELECT 'SIM_FOTO', FOT_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_FOTO
                UNION 
                SELECT 'SIM_GESTION_EXHIBICION', GEE_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_GESTION_EXHIBICION
                UNION 
                SELECT 'SIM_INVENTARIO', INV_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_INVENTARIO
                UNION 
                SELECT 'SIM_NOTA', NOT_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_NOTA
                UNION 
                SELECT 'SIM_RECORDATORIO', REC_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_RECORDATORIO
                UNION 
                SELECT 'SIM_RESPUESTA_USUARIO', REU_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_RESPUESTA_USUARIO
                UNION 
                SELECT 'SIM_RUTERO_VALORIZADO', RUV_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_RUTERO_VALORIZADO
                UNION 
                SELECT 'SIM_SEGUIMIENTO_GESTION_EXHIBICION', SGE_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_SEGUIMIENTO_GESTION_EXHIBICION
                UNION 
                SELECT 'SIM_SEGUIMIENTO_RUTA', SEG_RUTA_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_SEGUIMIENTO_RUTA
                UNION 
                SELECT 'SIM_SEGUIMIENTO_VENCIMIENTO', SEV_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_SEGUIMIENTO_VENCIMIENTO
                UNION 
                SELECT 'SIM_TRANSFERENCIA', TRA_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_TRANSFERENCIA
                UNION 
                SELECT 'SIM_TRAZA_RUTA', TRU_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_TRAZA_RUTA
                UNION 
                SELECT 'SIM_VENCIMIENTO', VEC_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_VENCIMIENTO
                UNION 
                SELECT 'SIM_VENTAS', VEN_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_VENTAS
                ) AS MDU ON MDU.RUT_CODIGO = RUT.RUT_CODIGO
        WHERE
            USC.CLI_CODIGO>=0 AND YEAR(RUT.RUT_FECHA_RUTA)>=2023) AS MOD
    PIVOT(
    MAX(MOD.NUMERO_REGISTROS)
    FOR MOD.MODULO IN ([SIM_ACOMPANANTE],[SIM_ACTIVIDAD_COMERCIAL],[SIM_AGOTADOS],[SIM_ASISTENCIA],[SIM_AUDITORIA],[SIM_CAMBIO_MARCA],[SIM_CAMBIO_PRODUCTO],[SIM_CAPACITACIONES],[SIM_CARAS],[SIM_CHEQUEO_PRECIO],[SIM_CHEQUEO_PRECIO_ESPECIAL],[SIM_CITA],[SIM_ENCABEZADO_MOVIMIENTO],[SIM_FOTO],[SIM_GESTION_EXHIBICION],[SIM_INVENTARIO],[SIM_NOTA],[SIM_RECORDATORIO],[SIM_RESPUESTA_USUARIO],[SIM_RUTERO_VALORIZADO],[SIM_SEGUIMIENTO_GESTION_EXHIBICION],[SIM_SEGUIMIENTO_RUTA],[SIM_SEGUIMIENTO_VENCIMIENTO],[SIM_TRANSFERENCIA],[SIM_TRAZA_RUTA],[SIM_VENCIMIENTO],[SIM_VENTAS])
    ) AS PIV)

SELECT DISTINCT
    YEAR(RUT.RUT_FECHA_RUTA) AS AÑO,
    MONTH(RUT.RUT_FECHA_RUTA) AS MES,
    USU.CLI_CODIGO,
    USU.CLI_NOMBRE,
    COUNT(RUT.RUT_CODIGO) OVER(PARTITION BY USU.CLI_CODIGO, YEAR(RUT.RUT_FECHA_RUTA), MONTH(RUT.RUT_FECHA_RUTA)) AS FRECUENCIA,
    PDV.#_PDV,
    PDV.#_USUARIOS,
    PRO.#_SKU,
    PRO.#_MARCA,
    SIM_ACOMPANANTE,
    SIM_ACTIVIDAD_COMERCIAL,
    SIM_AGOTADOS,
    SIM_ASISTENCIA,
    SIM_AUDITORIA,
    SIM_CAMBIO_MARCA,
    SIM_CAMBIO_PRODUCTO,
    SIM_CAPACITACIONES,
    SIM_CARAS,
    SIM_CHEQUEO_PRECIO,
    SIM_CHEQUEO_PRECIO_ESPECIAL,
    SIM_CITA,
    SIM_ENCABEZADO_MOVIMIENTO,
    SIM_FOTO,
    SIM_GESTION_EXHIBICION,
    SIM_INVENTARIO,
    SIM_NOTA,
    SIM_RECORDATORIO,
    SIM_RESPUESTA_USUARIO,
    SIM_RUTERO_VALORIZADO,
    SIM_SEGUIMIENTO_GESTION_EXHIBICION,
    SIM_SEGUIMIENTO_RUTA,
    SIM_SEGUIMIENTO_VENCIMIENTO,
    SIM_TRANSFERENCIA,
    SIM_TRAZA_RUTA,
    SIM_VENCIMIENTO,
    SIM_VENTAS
FROM
    USUARIOS AS USU
    INNER JOIN SIM_RUTA AS RUT ON RUT.USA_CODIGO=USU.USA_CODIGO AND RUT.ESTADO=1 AND RUT.TIP_CODIGO=32
    INNER JOIN PUNTOS AS PDV ON PDV.CLI_CODIGO=USU.CLI_CODIGO AND PDV.AÑO=YEAR(RUT.RUT_FECHA_RUTA) AND PDV.MES=MONTH(RUT.RUT_FECHA_RUTA)  
    INNER JOIN PRODUCTOS AS PRO ON PRO.CLI_CODIGO=USU.CLI_CODIGO AND PRO.AÑO=YEAR(RUT.RUT_FECHA_RUTA) AND PRO.MES=MONTH(RUT.RUT_FECHA_RUTA)  
    INNER JOIN MODULOS AS MOD ON MOD.CLI_CODIGO=USU.CLI_CODIGO AND MOD.AÑO=YEAR(RUT.RUT_FECHA_RUTA) AND MOD.MES=MONTH(RUT.RUT_FECHA_RUTA)  
WHERE
    MOD.CLI_CODIGO>=0 AND YEAR(RUT.RUT_FECHA_RUTA)>=2023