WITH NIVELES AS (
SELECT TIP_CODIGO,TIP_NOMBRE,CLACIFICACION_DE_EQUIPO,NIVEL_REQUERIMIENTO,HORA_ANALISTA,HORA_BD,DIA_DE_ENTREGA
FROM
(VALUES('42822',	'ACOMPAÑAMIENTOS',	'BD',	'1',	'4',	'6',	'1'),
('29563',	'ACTIVIDAD COMERCIAL',	'BD',	'1',	'4',	'6',	'1'),
('29562',	'CAUSAL DE NO VISITA',	'BD',	'1',	'4',	'6',	'1'),
('29569',	'PARAMETRIZACION DE EXHIBICIONES',	'BD',	'1',	'4',	'6',	'1'),
('42823',	'FOTO LIBRE',	'BD',	'1',	'4',	'6',	'1'),
('29559',	'URL DE MODELO BI',	'BD',	'1',	'4',	'6',	'1'),
('29565',	'INACTIVAR RUTAS',	'BD',	'1',	'4',	'6',	'1'),
('29551',	'USUARIOS',	'BD',	'1',	'4',	'6',	'1'),
('29567',	'CREACION DE ENCUESTA',	'EQUIPO',	'1',	'4',	'0',	'1'),
('56551',	'MODIFICACION ENCUESTA',	'BD',	'1',	'4',	'6',	'1'),
('29556',	'EDICION DE DATOS (EDICION DE CAPTURA)',	'BD',	'1',	'4',	'6',	'1'),
('56550',	'CARGUE DE RUTAS',	'EQUIPO',	'1',	'4',	'0',	'1'),
('29558',	'MODULOS DE VUM',	'BD',	'2',	'6',	'6',	'2'),
('29552',	'PARRILLAS',	'BD',	'2',	'6',	'6',	'2'),
('29561',	'PRODUCTOS',	'BD',	'2',	'6',	'6',	'2'),
('29566',	'VUM REQUEST',	'BD',	'2',	'4',	'6',	'2'),
('29555',	'CREACION DE ACTIVIDAD',	'BD',	'2',	'6',	'6',	'2'),
('56515',	'ALTAS Y BAJAS',	'EQUIPO',	'3',	'8',	'6',	'3'),
('29554',	'CREACION DE CLIENTE',	'BD',	'3',	'8',	'6',	'3'),
('56552',	'CARGUE DE EXHIBICIONES',	'EQUIPO',	'3',	'10',	'4',	'3'),
('29550',	'PUNTO DE VENTAS',	'BD-EQUIPO',	'3',	'8',	'6',	'3'),
('56553',	'VENCIMIENTOS',	'BD',	'1',	'4',	'6',	'1'),
('57144',       'CAPACITACIONES',       'EQUIPO',       '4',    '1',     '1',   '1')
) AS NIVELES_TICKETS(TIP_CODIGO,TIP_NOMBRE,CLACIFICACION_DE_EQUIPO,NIVEL_REQUERIMIENTO,HORA_ANALISTA,HORA_BD,DIA_DE_ENTREGA)
        )

SELECT
--TIK.CLI_CODIGO,
CLI.CLI_NOMBRE,
TIK.TIK_CODIGO,
--TIK.TIP_CODIGO AS TIP_ESTADO,
T1.TIP_NOMBRE AS ESTADO,
--TIK.TIP_CODIGO2 AS TIP_NOVEDAD,
T2.TIP_NOMBRE AS SOLICITUD,
TIK.USUARIO_CREACION AS USUARIO_SOLICITUD,
IIF(SOL.USUARIO_CREACION IS NULL,TTK.USUARIO_CREACION,SOL.USUARIO_CREACION) AS USUARIO_ASIGNADO,
CONVERT(DATE,TIK.FECHA_CREACION) AS FECHA_SOLICITUD,
IIF(CONVERT(DATE,SOL2.FECHA_CREACION) IS NULL,CONVERT(DATE,TTK.FECHA_CREACION),CONVERT(DATE,SOL2.FECHA_CREACION)) AS FECHA_ASIGNACION,
--TTK.TIP_CODIGO AS TIP_TRATAMIENTO,
T3.TIP_NOMBRE AS TRATAMIENTO,
TTK.USUARIO_CREACION AS USUARIO_RESPUESTA,
CONVERT(DATE,TTK.FECHA_CREACION) AS FECHA_RESPUESTA,
--TTK.FECHA_CREACION ,TIK.FECHA_CREACION,
DATEDIFF(DAY,TIK.FECHA_CREACION,TTK.FECHA_CREACION) AS DIAS_TRANSCURIDOS,
CONVERT(varchar, DATEADD(SECOND, DATEDIFF(SECOND, TIK.FECHA_CREACION, TTK.FECHA_CREACION), 0), 108) AS HORAS_TRANSCURIDAS,
NVL.NIVEL_REQUERIMIENTO,

CASE 
        WHEN DATEPART(WEEKDAY, TIK.FECHA_CREACION) = 6 AND DATEPART(WEEKDAY, TTK.FECHA_CREACION) = 2 THEN 'TICKET EN TIEMPOS'
        ELSE IIF(DATEDIFF(DAY, TIK.FECHA_CREACION, TTK.FECHA_CREACION) <= NVL.NIVEL_REQUERIMIENTO, 'TICKET EN TIEMPOS', 'TICKET FUERA DE TIEMPOS')
END AS ESTADO_EJECUCION,

CASE 
        WHEN T1.TIP_NOMBRE LIKE 'ABIERTO%' THEN 'TICKET SIN ASIGNAR'
        WHEN T1.TIP_NOMBRE LIKE 'TRANSFERIDO A ANALISTA BASES DE DATOS%' THEN 'TICKET EN TRAMITE POR BD'
        WHEN T1.TIP_NOMBRE LIKE 'TRANSFERIDO%' THEN 'TICKET EN TRAMITE'
        WHEN T1.TIP_NOMBRE LIKE 'PROCESADO%' THEN 'TICKET EN TRAMITE'
        WHEN T1.TIP_NOMBRE LIKE 'ANULADO%' THEN 'TICKET ANULADO'
        WHEN T1.TIP_NOMBRE LIKE 'TICKET CON ERRORES%' THEN 'TICKET PROCESADO CON ERRORES'
        WHEN T1.TIP_NOMBRE LIKE 'TICKET CERRADO%' THEN 'TICKET CERRADO'
        ELSE 'ESTADO DESCONOCIDO'
END AS ESTADO_TICKET

FROM
SIM_TICKET AS TIK
INNER JOIN SIM_TIPO AS T1 ON T1.TIP_CODIGO=TIK.TIP_CODIGO
INNER JOIN SIM_TIPO AS T2 ON T2.TIP_CODIGO=TIK.TIP_CODIGO2
INNER JOIN (    SELECT
        TTK_CODIGO,
        TIK_CODIGO,
        TIP_CODIGO,
        USUARIO_CREACION,
        FECHA_CREACION,
        ESTADO,
        ROW_NUMBER() OVER (PARTITION BY TIK_CODIGO ORDER BY FECHA_CREACION DESC) AS rn
    FROM
        SIM_TRATAMIENTO_TICKET) AS TTK ON TTK.TIK_CODIGO=TIK.TIK_CODIGO
INNER JOIN SIM_TIPO AS T3 ON T3.TIP_CODIGO=TTK.TIP_CODIGO
LEFT JOIN NIVELES AS NVL ON NVL.TIP_CODIGO=TIK.TIP_CODIGO2
LEFT JOIN (SELECT
        TTK.TTK_CODIGO,
        TTK.TIK_CODIGO,
        TTK.TIP_CODIGO,
        TTK.USUARIO_CREACION,
        TTK.FECHA_CREACION,
        TTK.ESTADO,
        ROW_NUMBER() OVER (PARTITION BY TTK.TIK_CODIGO ORDER BY TTK.FECHA_CREACION DESC) AS CONTEO
    FROM
        SIM_TRATAMIENTO_TICKET AS TTK
        INNER JOIN SIM_USUARIO AS USU ON USU.USU_LOGIN=TTK.USUARIO_CREACION AND USU_DIRECCION='ANALISTA BACK')
        AS SOL ON SOL.TIK_CODIGO=TIK.TIK_CODIGO AND SOL.CONTEO=1
INNER JOIN SIM_CLIENTE AS CLI ON CLI.CLI_CODIGO=TIK.CLI_CODIGO
LEFT JOIN (SELECT
        TTK.TTK_CODIGO,
        TTK.TIK_CODIGO,
        TTK.TIP_CODIGO,
        TTK.USUARIO_CREACION,
        TTK.FECHA_CREACION,
        TTK.ESTADO,
        ROW_NUMBER() OVER (PARTITION BY TTK.TIK_CODIGO ORDER BY TTK.FECHA_CREACION ASC) AS CONTEO
    FROM
        SIM_TRATAMIENTO_TICKET AS TTK
        INNER JOIN SIM_USUARIO AS USU ON USU.USU_LOGIN=TTK.USUARIO_CREACION AND USU_DIRECCION='ANALISTA BACK')
        AS SOL2 ON SOL2.TIK_CODIGO=TIK.TIK_CODIGO AND SOL2.CONTEO=1
WHERE 
TIK.ESTADO=1 AND  TTK.ESTADO=1 AND TTK.rn = 1
AND CONVERT(DATE,TIK.FECHA_CREACION) >= '2024-06-01'
ORDER BY TIK.TIK_CODIGO, TTK.TTK_CODIGO