SELECT
T4.TIP_NOMBRE AS CLIENTE,
TSS.TSS_CODIGO,
--T1.TIP_NOMBRE AS TEMA,
T2.TIP_NOMBRE AS TIPO,
TSS.USUARIO_CREACION AS USUARIO_SOLICITUD,
TSS.FECHA_CREACION AS FECHA_SOLICITUD,
TTS.USUARIO_MODIFICACION AS USUARIO_RESPUESTA,
TTS.FECHA_MODIFICACION AS FECHA_RESPUESTA,
T3.TIP_NOMBRE AS ESTADO_SOLICITUD
FROM
SIM_TICKET_SOLICITUD_SERVICIO AS TSS
--INNER JOIN SIM_TIPO AS T1 ON T1.TIP_CODIGO=TSS.TIP_CODIGO
INNER JOIN SIM_TIPO AS T2 ON T2.TIP_CODIGO=TSS.TIP_CODIGO2
INNER JOIN (    SELECT
        TTS.TTS_CODIGO,
        TTS.TSS_CODIGO,
        TTS.TIP_CODIGO,
        TTS.TIP_CODIGO2,
        TTS.USUARIO_CREACION,
        TTS.FECHA_CREACION,
        TTS.USUARIO_MODIFICACION,
        TTS.FECHA_MODIFICACION,
        TTS.ESTADO,
        ROW_NUMBER() OVER (PARTITION BY TTS.TSS_CODIGO ORDER BY TTS.FECHA_CREACION DESC) AS RN
    FROM
        SIM_TRATAMIENTO_TICKET_SOLICITUD_SERVICIO AS TTS
        INNER JOIN SIM_TICKET_SOLICITUD_SERVICIO AS TSS ON TSS.TSS_CODIGO=TTS.TSS_CODIGO
    WHERE    
        TSS.ESTADO=1 AND TSS.ACT_CODIGO=392) AS TTS ON TSS.TSS_CODIGO=TTS.TSS_CODIGO AND RN=1
INNER JOIN SIM_TIPO AS T3 ON T3.TIP_CODIGO=TTS.TIP_CODIGO2
INNER JOIN SIM_TICKET_SOLICITUD_REGIONAL AS TSR ON TSR.TSS_CODIGO=TSS.TSS_CODIGO
INNER JOIN SIM_TIPO AS T4 ON T4.TIP_CODIGO=TSR.TIP_CODIGO
WHERE 
TSS.ESTADO=1 AND TSS.ACT_CODIGO=392 AND CONVERT(DATE,TSS.FECHA_CREACION)>='2024-07-01'