WITH PANEL AS(
        SELECT PVC.PVC_CODIGO,PVC.PDV_CODIGO,PVC.ACT_CODIGO,PVC.PVC_NOMBRE_PDV,PVC.TIP_CODIGO AS TIP_CODIGO 
        FROM SIM_PUNTO_VENTA_CLIENTE AS PVC 
                INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON ACA.ACT_CODIGO=PVC.ACT_CODIGO AND ACA.ESTADO=1
                INNER JOIN SIM_ENCABEZADO_PARRILLA AS ENP ON ENP.ACA_CODIGO=ACA.ACA_CODIGO AND ENP.ESTADO=1
        WHERE PVC.ESTADO=1
UNION
        SELECT PVC.PVC_CODIGO,PVC.PDV_CODIGO,PVC.ACT_CODIGO,PVC.PVC_NOMBRE_PDV,PVC.TIP_CODIGO2
        FROM SIM_PUNTO_VENTA_CLIENTE AS PVC 
                INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON ACA.ACT_CODIGO=PVC.ACT_CODIGO AND ACA.ESTADO=1
                INNER JOIN SIM_ENCABEZADO_PARRILLA AS ENP ON ENP.ACA_CODIGO=ACA.ACA_CODIGO AND ENP.ESTADO=1
        WHERE PVC.ESTADO=1
UNION
        SELECT PVC.PVC_CODIGO,PVC.PDV_CODIGO,PVC.ACT_CODIGO,PVC.PVC_NOMBRE_PDV,PVC.TIP_CODIGO3
        FROM SIM_PUNTO_VENTA_CLIENTE AS PVC 
                INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON ACA.ACT_CODIGO=PVC.ACT_CODIGO AND ACA.ESTADO=1
                INNER JOIN SIM_ENCABEZADO_PARRILLA AS ENP ON ENP.ACA_CODIGO=ACA.ACA_CODIGO AND ENP.ESTADO=1
        WHERE PVC.ESTADO=1
UNION
        SELECT PVC.PVC_CODIGO,PVC.PDV_CODIGO,PVC.ACT_CODIGO,PVC.PVC_NOMBRE_PDV,PVC.TIP_CODIGO5
        FROM SIM_PUNTO_VENTA_CLIENTE AS PVC 
                INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON ACA.ACT_CODIGO=PVC.ACT_CODIGO AND ACA.ESTADO=1
                INNER JOIN SIM_ENCABEZADO_PARRILLA AS ENP ON ENP.ACA_CODIGO=ACA.ACA_CODIGO AND ENP.ESTADO=1
        WHERE PVC.ESTADO=1
UNION
        SELECT PVC.PVC_CODIGO,PVC.PDV_CODIGO,PVC.ACT_CODIGO,PVC.PVC_NOMBRE_PDV,PVC.TIP_CODIGO6
        FROM SIM_PUNTO_VENTA_CLIENTE AS PVC 
                INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON ACA.ACT_CODIGO=PVC.ACT_CODIGO AND ACA.ESTADO=1
                INNER JOIN SIM_ENCABEZADO_PARRILLA AS ENP ON ENP.ACA_CODIGO=ACA.ACA_CODIGO AND ENP.ESTADO=1
        WHERE PVC.ESTADO=1),
        TIPOS_PARRILLA AS (
        SELECT
        ENP.ENP_CODIGO,ACA.ACT_CODIGO,ENP.ENP_NOMBRE,APV.APV_NOMBRE AS MODULO,
        COALESCE(ENP.TIP_CODIGO,ENP.TIP_CODIGO2,ENP.TIP_CODIGO3,ENP.TIP_CODIGO4,ENP.TIP_CODIGO5,ENP.TIP_CODIGO6) AS TIP_CODIGO
        FROM SIM_ENCABEZADO_PARRILLA AS ENP
                INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON ACA.ACA_CODIGO=ENP.ACA_CODIGO AND ACA.ESTADO=1
                INNER JOIN SIM_ACCION_PUNTO_VENTA AS APV ON APV.APV_CODIGO=ACA.APV_CODIGO AND APV.ESTADO=1
        WHERE ENP.ESTADO=1)
SELECT
        CLI.CLI_CODIGO AS 'CODIGO CLIENTE',
        CLI.CLI_NOMBRE AS 'NOMBRE CLIENTE',
        ACT.ACT_CODIGO AS 'CODIGO ACTIVIDAD',
        ACT.ACT_NOMBRE AS 'NOMBRE ACTIVIDAD',
        PVC.PDV_CODIGO AS 'CODIGO PDV',
        PVC.PVC_NOMBRE_PDV AS 'NOMBRE PDV',
        PVC.TIP_CODIGO AS 'TIPO PARRILLA',
        TIP.TIP_NOMBRE AS 'NOMBRE TIPO',
        CLT.CLT_NOMBRE AS 'CLASE TIPO',
        ENP.ENP_CODIGO AS 'CODIGO PARRILLA',
        ENP.ENP_NOMBRE AS 'NOMBRE PARRILLA',
        UPPER(ENP.MODULO) AS MODULO
FROM
        SIM_CLIENTE AS CLI
INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.CLI_CODIGO = CLI.CLI_CODIGO AND ACT.ESTADO = 1
INNER JOIN PANEL AS PVC ON PVC.ACT_CODIGO=ACT.ACT_CODIGO AND ACT.ESTADO=1
INNER JOIN TIPOS_PARRILLA AS ENP ON ENP.ACT_CODIGO=PVC.ACT_CODIGO AND ENP.TIP_CODIGO=PVC.TIP_CODIGO
INNER JOIN SIM_TIPO AS TIP ON TIP.TIP_CODIGO=PVC.TIP_CODIGO
INNER JOIN SIM_CLASE_TIPO AS CLT ON CLT.CLT_CODIGO=TIP.CLT_CODIGO
WHERE
    CLI.ESTADO = 1 
    AND CLI.CLI_CODIGO NOT IN (1,161,162,163,165,166,167,168,169,170,171,172,173,174,176,177,178,179,180,181,182,183,184,185,187,188,189,191,192,193,194,195,196,197,198,200,201,202,97,190)
