WITH SIM_USUARIOS AS(
SELECT
    ACT.CLI_CODIGO,
    ACT.CLI_NOMBRE,
    ACT.ACT_CODIGO,
    ACT.ACT_NOMBRE,
    USU.USU_CODIGO,
    UPPER(USU.USU_NOMBRES + ' ' + USU.USU_APELLIDOS) AS NOMBRE_COMPLETO,
    USU.USU_NUMERO_DOCUMENTO AS #_DOCUEMNTO,
    LOWER(USU.USU_LOGIN) AS LOGIN,
    PER.PER_CODIGO,
    PER.PER_NOMBRE AS PERFIL,
    USC.USC_CODIGO,
    USA.USA_CODIGO,
    PEU.PEU_CODIGO,
    CASE
    WHEN USA.ESTADO=0 AND USC.ESTADO=0 THEN 'CLIANTE-ACTIVIDAD INACTIVO'
    WHEN USC.ESTADO=1 AND USA.ESTADO=0 THEN 'CLIENTE-ACTIVO Y ACTIVIDAD-INACTIVA'
    WHEN USC.ESTADO=0 AND USA.ESTADO=1 THEN 'CLIENTE-INACTIVO Y ACTIVIDAD-ACTIVA'
    WHEN USC.ESTADO=1 AND USA.ESTADO=1 THEN 'ACTIVO'
    ELSE 'HAY NOVEDADES'
    END AS ESTADO
FROM
    SIM_USUARIO AS USU
    LEFT JOIN SIM_USUARIO_CLIENTE AS USC ON USC.USU_CODIGO=USU.USU_CODIGO
    LEFT JOIN SIM_USUARIO_ACTIVIIDAD AS USA ON USA.USC_CODIGO=USC.USC_CODIGO
    LEFT JOIN SIM_PERFIL_USUARIO AS PEU ON PEU.USA_CODIGO=USA.USA_CODIGO AND PEU.ESTADO=1
    LEFT JOIN SIM_PERFIL AS PER ON PER.PER_CODIGO=PEU.PER_CODIGO
    LEFT JOIN (SELECT CLI.CLI_CODIGO,CLI.CLI_NOMBRE,ACT.ACT_CODIGO,ACT.ACT_NOMBRE
                FROM SIM_CLIENTE AS CLI INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.CLI_CODIGO=CLI.CLI_CODIGO) 
                AS ACT ON ACT.ACT_CODIGO=USA.ACT_CODIGO
WHERE
    PEU.PEU_CODIGO IS NOT NULL
)

SELECT DISTINCT
USU.CLI_NOMBRE,
LOA.USUARIO_CREACION,
LOA.LOA_MENSAJE,
CONVERT(DATE,LOA.FECHA_CREACION) AS FECHA,
FORMAT(LOA.FECHA_CREACION,'HH:mm:ss') AS HORA
FROM
SIM_LOG_ACCIONES AS LOA
INNER JOIN SIM_USUARIOS AS USU ON USU.USC_CODIGO=LOA.USC_CODIGO
WHERE
USU.CLI_CODIGO=11 AND YEAR(FECHA_CREACION)=YEAR(GETDATE()) AND MONTH(FECHA_CREACION)=5