BEGIN TRANSACTION;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT *
FROM OPENQUERY([10.1.0.7], 'SELECT [ENRE_CODIGO]
      ,[ENRE_COD_EN]
      ,[ENRE_CEDULA]
      ,[ENRE_EMPRESA]
      ,[ENRE_CONTRATO]
      ,[FECHA_CREACION]
      ,[COD_EPR]
      ,[EPR_DESCRIPCION]
      ,[ER_DESCRIPCION]
      ,[RESPUESTA_ABIERTA]
  FROM [ESmad].[dbo].[QV_ENCUESTA_RETIRO_GENERICO] WITH(NOLOCK)')
COMMIT TRANSACTION;