BEGIN TRANSACTION;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT *
FROM OPENQUERY([10.1.0.7], 'SELECT [RET_CODIGO]
      ,[EMP_CODIGO]
      ,[RET_CEDULA]
      ,[RET_CONTRATO]
      ,[RET_CENTRO_COSTOS]
      ,[RET_NIVEL3]
      ,[RET_FECHA_RETIRO]
      ,[RET_MOTIVO_RETIRO]
      ,[SUB_MOTIVO]
      ,[RET_OBSERVACIONES]
      ,[ESTADO]
      ,[USUARIO_CREACION]
      ,[FECHA_CREACION]
      ,[RET_PAZ_SALVO]
      ,[PAZ]
      ,[ESTADO_RETIRO]
      ,[EXTEMPORANEO]
      ,[nom_empl]
      ,[ape_empl]
      ,[nom_nive]
      ,[NIT_CLIE]
      ,[tip_remu]
      ,[nom_mdej]
      ,[ind_acti]
      ,[nom_ccos]
      ,[cod_ccos]
      ,[FECHA_INGRESO]
      ,[DIAS_LABORADO]
      ,[COD_RET_MOTIVO_RETIRO]
      ,[COD_SUB_MOTIVO]
      ,[FECHA_MODIFICACION]
      ,[ACTUALIZACION]
      ,[fe_no]
  FROM [ESmad].[dbo].[QV_RETIROS_GENERICO] WITH(NOLOCK)')
COMMIT TRANSACTION;