SELECT DISTINCT

CLI.CLI_CODIGO,
CLI.CLI_NOMBRE,
PRA.ACT_CODIGO,
ACT.ACT_NOMBRE,
PRA.PRA_CODIGO,
PRA.PRO_CODIGO,
PRO.PRO_NOMBRE,
PRO.MAR_CODIGO,
MAR.MAR_NOMBRE,
MAR.MAR_PROPIA,
PAA.PAA_CODIGO,
ACA.ACA_CODIGO,

CASE
WHEN MAR.MAR_PROPIA=0 AND PAA.PAA_CODIGO > 0 THEN 'EL PRODUCTO ES MARCA COMPETENCIA ESTA EN VENCIMIENTOS'
WHEN MAR.MAR_PROPIA=1 AND PAA.PAA_CODIGO IS NULL THEN 'EL PRODUCTO NO SE ENCUENTRA EN VENCIMIENTOS'
WHEN MAR.MAR_PROPIA=0 AND PAA.PAA_CODIGO IS NULL THEN 'EL PRODUCTO MARCA COMPETENCIA NO ESTA EN VENCIMIENTOS'
ELSE 'PRODUCTO EN VENCIMIENTOS' END AS ESTADO_PRODUCTO

FROM
SIM_PRODUCTO_ACTIVIDAD AS PRA
INNER JOIN SIM_ACTIVIDAD AS ACT ON (ACT.ACT_CODIGO=PRA.ACT_CODIGO)
INNER JOIN SIM_CLIENTE AS CLI ON (CLI.CLI_CODIGO=ACT.CLI_CODIGO)
INNER JOIN SIM_PRODUCTO AS PRO ON (PRA.PRO_CODIGO=PRO.PRO_CODIGO)
INNER JOIN SIM_MARCA AS MAR ON (MAR.MAR_CODIGO=PRO.MAR_CODIGO)
FULL JOIN SIM_PRODUCTO_ACCION_ACTIVIDAD AS PAA ON (PAA.PRA_CODIGO=PRA.PRA_CODIGO)
INNER JOIN SIM_ACCION_ACTIVIDAD AS ACA ON (ACA.ACT_CODIGO=PRA.ACT_CODIGO)

WHERE
PRA.ESTADO=1 AND CLI.ESTADO=1 AND ACT.ESTADO=1 AND PRO.ESTADO=1 AND (PAA.ESTADO IS NULL OR PAA.ESTADO=1) AND ACA.APV_CODIGO IN (9) AND ACA.ESTADO=1

ORDER BY CLI.CLI_CODIGO,PRA.ACT_CODIGO,PRO.MAR_CODIGO,PRA.PRO_CODIGO