SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

WITH MODULOS AS (
    SELECT 'SIM_RUTA' AS MODULO, RUT_CODIGO AS PKEY, RUT_CODIGO, FECHA_CREACION FROM SIM_RUTA 
    UNION 
    SELECT 'SIM_ACOMPANANTE', ACP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ACOMPANANTE
    UNION 
    SELECT 'SIM_ACTIVIDAD_COMERCIAL', ACO_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ACTIVIDAD_COMERCIAL
    UNION 
    SELECT 'SIM_AGOTADOS', AGO_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_AGOTADOS
    UNION 
    SELECT 'SIM_ASISTENCIA', ASI_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ASISTENCIA
    UNION 
    SELECT 'SIM_AUDITORIA', AUD_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_AUDITORIA
    UNION 
    SELECT 'SIM_CAMBIO_MARCA', CAM_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CAMBIO_MARCA
    UNION 
    SELECT 'SIM_CAMBIO_PRODUCTO', CAP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CAMBIO_PRODUCTO
    UNION 
    SELECT 'SIM_CAPACITACIONES', CAP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CAPACITACIONES
    UNION 
    SELECT 'SIM_CARAS', CAR_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CARAS
    UNION 
    SELECT 'SIM_CHEQUEO_PRECIO', CHP_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CHEQUEO_PRECIO
    UNION 
    SELECT 'SIM_CHEQUEO_PRECIO_ESPECIAL', CPE_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CHEQUEO_PRECIO_ESPECIAL
    UNION 
    SELECT 'SIM_CITA', CIT_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_CITA
    UNION 
    SELECT 'SIM_ENCABEZADO_MOVIMIENTO', ENM_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_ENCABEZADO_MOVIMIENTO
    UNION 
    SELECT 'SIM_FOTO', FOT_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_FOTO
    UNION 
    SELECT 'SIM_GESTION_EXHIBICION', GEE_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_GESTION_EXHIBICION
    UNION 
    SELECT 'SIM_INVENTARIO', INV_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_INVENTARIO
    UNION 
    SELECT 'SIM_NOTA', NOT_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_NOTA
    UNION 
    SELECT 'SIM_RECORDATORIO', REC_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_RECORDATORIO
    UNION 
    SELECT 'SIM_RESPUESTA_USUARIO', REU_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_RESPUESTA_USUARIO
    UNION 
    SELECT 'SIM_RUTERO_VALORIZADO', RUV_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_RUTERO_VALORIZADO
    UNION 
    SELECT 'SIM_SEGUIMIENTO_GESTION_EXHIBICION', SGE_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_SEGUIMIENTO_GESTION_EXHIBICION
    UNION 
    SELECT 'SIM_SEGUIMIENTO_RUTA', SEG_RUTA_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_SEGUIMIENTO_RUTA
    UNION 
    SELECT 'SIM_SEGUIMIENTO_VENCIMIENTO', SEV_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_SEGUIMIENTO_VENCIMIENTO
    UNION 
    SELECT 'SIM_TRANSFERENCIA', TRA_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_TRANSFERENCIA
    UNION 
    SELECT 'SIM_TRAZA_RUTA', TRU_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_TRAZA_RUTA
    UNION 
    SELECT 'SIM_VENCIMIENTO', VEC_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_VENCIMIENTO
    UNION 
    SELECT 'SIM_VENTAS', VEN_CODIGO, RUT_CODIGO, FECHA_CREACION FROM SIM_VENTAS
)
SELECT
    CLI.CLI_CODIGO,
    CLI.CLI_NOMBRE AS CLIENTE, 
    ACT.ACT_CODIGO, 
    ACT.ACT_NOMBRE AS ACTIVIDAD, 
    MDU.MODULO,
    MIN(MDU.FECHA_CREACION) AS PRIMERA_FECHA_CAPTURA,
    MAX(MDU.FECHA_CREACION) AS ULTIMA_FECHA_CAPTURA,
    COUNT(MDU.PKEY) AS NUMERO_REGISTROS
FROM
    SIM_USUARIO_ACTIVIIDAD AS USA
INNER JOIN SIM_ACTIVIDAD AS ACT ON ACT.ACT_CODIGO = USA.ACT_CODIGO
INNER JOIN SIM_CLIENTE AS CLI ON CLI.CLI_CODIGO = ACT.CLI_CODIGO
INNER JOIN SIM_USUARIO_CLIENTE AS USC ON USC.USC_CODIGO = USA.USC_CODIGO
INNER JOIN SIM_RUTA AS RUT ON RUT.USA_CODIGO = USA.USA_CODIGO
INNER JOIN MODULOS AS MDU ON MDU.RUT_CODIGO = RUT.RUT_CODIGO
WHERE
    USC.CLI_CODIGO IN (24, 84)
GROUP BY
    CLI.CLI_CODIGO,
    CLI.CLI_NOMBRE,
    ACT.ACT_CODIGO,
    ACT.ACT_NOMBRE,
    MDU.MODULO
ORDER BY
    CLI.CLI_CODIGO,
    ACT.ACT_CODIGO,
    MDU.MODULO;